BEGIN;
ALTER TABLE imet.imet_countries
    ADD COLUMN name_pt text COLLATE pg_catalog."default";

UPDATE imet.imet_countries SET name_pt='Aruba' WHERE iso2 = 'AW';
UPDATE imet.imet_countries SET name_pt='Afeganistão' WHERE iso2 = 'AF';
UPDATE imet.imet_countries SET name_pt='Angola' WHERE iso2 = 'AO';
UPDATE imet.imet_countries SET name_pt='Anguilla ' WHERE iso2 = 'AI';
UPDATE imet.imet_countries SET name_pt='Ilhas Aland' WHERE iso2 = 'AX';
UPDATE imet.imet_countries SET name_pt='Albânia' WHERE iso2 = 'AL';
UPDATE imet.imet_countries SET name_pt='Andorra' WHERE iso2 = 'AD';
UPDATE imet.imet_countries SET name_pt='Antilhas Holandesas      ' WHERE iso2 = 'AN';
UPDATE imet.imet_countries SET name_pt='Emirados Árabes Unidos' WHERE iso2 = 'AE';
UPDATE imet.imet_countries SET name_pt='Argentina' WHERE iso2 = 'AR';
UPDATE imet.imet_countries SET name_pt='Armênia' WHERE iso2 = 'AM';
UPDATE imet.imet_countries SET name_pt='Samoa Americana' WHERE iso2 = 'AS';
UPDATE imet.imet_countries SET name_pt='Antártica' WHERE iso2 = 'AQ';
UPDATE imet.imet_countries SET name_pt='Territórios do Sul da França' WHERE iso2 = 'TF';
UPDATE imet.imet_countries SET name_pt='Antiga e barbuda' WHERE iso2 = 'AG';
UPDATE imet.imet_countries SET name_pt='Austrália' WHERE iso2 = 'AU';
UPDATE imet.imet_countries SET name_pt='Áustria' WHERE iso2 = 'AT';
UPDATE imet.imet_countries SET name_pt='Tão Tão Distante' WHERE iso2 = 'WY';
UPDATE imet.imet_countries SET name_pt='Azerbaijão' WHERE iso2 = 'AZ';
UPDATE imet.imet_countries SET name_pt='Burundi' WHERE iso2 = 'BI';
UPDATE imet.imet_countries SET name_pt='Bélgica' WHERE iso2 = 'BE';
UPDATE imet.imet_countries SET name_pt='Benin' WHERE iso2 = 'BJ';
UPDATE imet.imet_countries SET name_pt='Burkina faso' WHERE iso2 = 'BF';
UPDATE imet.imet_countries SET name_pt='Bangladesh' WHERE iso2 = 'BD';
UPDATE imet.imet_countries SET name_pt='Bulgária' WHERE iso2 = 'BG';
UPDATE imet.imet_countries SET name_pt='Bahrein' WHERE iso2 = 'BH';
UPDATE imet.imet_countries SET name_pt='Bahamas' WHERE iso2 = 'BS';
UPDATE imet.imet_countries SET name_pt='Bósnia e Herzegovina' WHERE iso2 = 'BA';
UPDATE imet.imet_countries SET name_pt='Bielo-Rússia' WHERE iso2 = 'BY';
UPDATE imet.imet_countries SET name_pt='Belize' WHERE iso2 = 'BZ';
UPDATE imet.imet_countries SET name_pt='Bermudas' WHERE iso2 = 'BM';
UPDATE imet.imet_countries SET name_pt='Bolívia' WHERE iso2 = 'BO';
UPDATE imet.imet_countries SET name_pt='Brasil' WHERE iso2 = 'BR';
UPDATE imet.imet_countries SET name_pt='Barbados' WHERE iso2 = 'BB';
UPDATE imet.imet_countries SET name_pt='Brunei Darussalam' WHERE iso2 = 'BN';
UPDATE imet.imet_countries SET name_pt='Butão' WHERE iso2 = 'BT';
UPDATE imet.imet_countries SET name_pt='Ilha Bouvet' WHERE iso2 = 'BV';
UPDATE imet.imet_countries SET name_pt='Botswana' WHERE iso2 = 'BW';
UPDATE imet.imet_countries SET name_pt='República Centro-Africano' WHERE iso2 = 'CF';
UPDATE imet.imet_countries SET name_pt='Canadá' WHERE iso2 = 'CA';
UPDATE imet.imet_countries SET name_pt='Ilhas Cocos (Keeling)' WHERE iso2 = 'CC';
UPDATE imet.imet_countries SET name_pt='Suíço' WHERE iso2 = 'CH';
UPDATE imet.imet_countries SET name_pt='Pimenta' WHERE iso2 = 'CL';
UPDATE imet.imet_countries SET name_pt='China' WHERE iso2 = 'CN';
UPDATE imet.imet_countries SET name_pt='Costa do Marfim' WHERE iso2 = 'CI';
UPDATE imet.imet_countries SET name_pt='Camarões' WHERE iso2 = 'CM';
UPDATE imet.imet_countries SET name_pt='República Democrática do Congo' WHERE iso2 = 'CD';
UPDATE imet.imet_countries SET name_pt='Congo' WHERE iso2 = 'CG';
UPDATE imet.imet_countries SET name_pt='Ilhas Cook' WHERE iso2 = 'CK';
UPDATE imet.imet_countries SET name_pt='Colômbia' WHERE iso2 = 'CO';
UPDATE imet.imet_countries SET name_pt='Comores' WHERE iso2 = 'KM';
UPDATE imet.imet_countries SET name_pt='Cabo Verde' WHERE iso2 = 'CV';
UPDATE imet.imet_countries SET name_pt='Costa Rica' WHERE iso2 = 'CR';
UPDATE imet.imet_countries SET name_pt='Cuba' WHERE iso2 = 'CU';
UPDATE imet.imet_countries SET name_pt='Ilha do Natal' WHERE iso2 = 'CX';
UPDATE imet.imet_countries SET name_pt='Ilhas Cayman' WHERE iso2 = 'KY';
UPDATE imet.imet_countries SET name_pt='Chipre' WHERE iso2 = 'CY';
UPDATE imet.imet_countries SET name_pt='Czechia' WHERE iso2 = 'CZ';
UPDATE imet.imet_countries SET name_pt='Alemanha' WHERE iso2 = 'DE';
UPDATE imet.imet_countries SET name_pt='Djibouti' WHERE iso2 = 'DJ';
UPDATE imet.imet_countries SET name_pt='Dominica' WHERE iso2 = 'DM';
UPDATE imet.imet_countries SET name_pt='Dinamarca' WHERE iso2 = 'DK';
UPDATE imet.imet_countries SET name_pt='República Dominicana' WHERE iso2 = 'DO';
UPDATE imet.imet_countries SET name_pt='Argélia' WHERE iso2 = 'DZ';
UPDATE imet.imet_countries SET name_pt='Equador' WHERE iso2 = 'EC';
UPDATE imet.imet_countries SET name_pt='Egito' WHERE iso2 = 'EG';
UPDATE imet.imet_countries SET name_pt='Eritreia' WHERE iso2 = 'ER';
UPDATE imet.imet_countries SET name_pt='Saara Ocidental' WHERE iso2 = 'EH';
UPDATE imet.imet_countries SET name_pt='Espanha' WHERE iso2 = 'ES';
UPDATE imet.imet_countries SET name_pt='Estônia' WHERE iso2 = 'EE';
UPDATE imet.imet_countries SET name_pt='Etiópia' WHERE iso2 = 'ET';
UPDATE imet.imet_countries SET name_pt='Finlândia' WHERE iso2 = 'FI';
UPDATE imet.imet_countries SET name_pt='Fiji' WHERE iso2 = 'FJ';
UPDATE imet.imet_countries SET name_pt='Ilhas Malvinas' WHERE iso2 = 'FK';
UPDATE imet.imet_countries SET name_pt='França' WHERE iso2 = 'FR';
UPDATE imet.imet_countries SET name_pt='Ilhas Faroe' WHERE iso2 = 'FO';
UPDATE imet.imet_countries SET name_pt='Micronésia' WHERE iso2 = 'FM';
UPDATE imet.imet_countries SET name_pt='Gabão' WHERE iso2 = 'GA';
UPDATE imet.imet_countries SET name_pt='Reino Unido' WHERE iso2 = 'GB';
UPDATE imet.imet_countries SET name_pt='Georgia' WHERE iso2 = 'GE';
UPDATE imet.imet_countries SET name_pt='Gana' WHERE iso2 = 'GH';
UPDATE imet.imet_countries SET name_pt='Gibraltar' WHERE iso2 = 'GI';
UPDATE imet.imet_countries SET name_pt='Guiné' WHERE iso2 = 'GN';
UPDATE imet.imet_countries SET name_pt='Guadalupe' WHERE iso2 = 'GP';
UPDATE imet.imet_countries SET name_pt='Gâmbia' WHERE iso2 = 'GM';
UPDATE imet.imet_countries SET name_pt='Guiné-Bissau' WHERE iso2 = 'GW';
UPDATE imet.imet_countries SET name_pt='Guiné Equatorial' WHERE iso2 = 'GQ';
UPDATE imet.imet_countries SET name_pt='Grécia' WHERE iso2 = 'GR';
UPDATE imet.imet_countries SET name_pt='Grenade' WHERE iso2 = 'GD';
UPDATE imet.imet_countries SET name_pt='Groenlândia' WHERE iso2 = 'GL';
UPDATE imet.imet_countries SET name_pt='Guatemala' WHERE iso2 = 'GT';
UPDATE imet.imet_countries SET name_pt='Guiné Francesa' WHERE iso2 = 'GF';
UPDATE imet.imet_countries SET name_pt='Guam' WHERE iso2 = 'GU';
UPDATE imet.imet_countries SET name_pt='Guiana' WHERE iso2 = 'GY';
UPDATE imet.imet_countries SET name_pt='Hong Kong' WHERE iso2 = 'HK';
UPDATE imet.imet_countries SET name_pt='Ilhas Heard e Ilhas McDonald' WHERE iso2 = 'HM';
UPDATE imet.imet_countries SET name_pt='Honduras' WHERE iso2 = 'HN';
UPDATE imet.imet_countries SET name_pt='Croácia' WHERE iso2 = 'HR';
UPDATE imet.imet_countries SET name_pt='Haiti' WHERE iso2 = 'HT';
UPDATE imet.imet_countries SET name_pt='Hungria' WHERE iso2 = 'HU';
UPDATE imet.imet_countries SET name_pt='Indonésia' WHERE iso2 = 'ID';
UPDATE imet.imet_countries SET name_pt='Ilha de Man' WHERE iso2 = 'IM';
UPDATE imet.imet_countries SET name_pt='Índia' WHERE iso2 = 'IN';
UPDATE imet.imet_countries SET name_pt='Território Oceânico da Índia Britânica' WHERE iso2 = 'IO';
UPDATE imet.imet_countries SET name_pt='Irlanda' WHERE iso2 = 'IE';
UPDATE imet.imet_countries SET name_pt='Irã' WHERE iso2 = 'IR';
UPDATE imet.imet_countries SET name_pt='Iraque' WHERE iso2 = 'IQ';
UPDATE imet.imet_countries SET name_pt='Islândia' WHERE iso2 = 'IS';
UPDATE imet.imet_countries SET name_pt='Israel' WHERE iso2 = 'IL';
UPDATE imet.imet_countries SET name_pt='Itália' WHERE iso2 = 'IT';
UPDATE imet.imet_countries SET name_pt='Jamaica' WHERE iso2 = 'JM';
UPDATE imet.imet_countries SET name_pt='Jordânia' WHERE iso2 = 'JO';
UPDATE imet.imet_countries SET name_pt='Japão' WHERE iso2 = 'JP';
UPDATE imet.imet_countries SET name_pt='Cazaquistão' WHERE iso2 = 'KZ';
UPDATE imet.imet_countries SET name_pt='Quênia' WHERE iso2 = 'KE';
UPDATE imet.imet_countries SET name_pt='Quirguistão' WHERE iso2 = 'KG';
UPDATE imet.imet_countries SET name_pt='Camboja' WHERE iso2 = 'KH';
UPDATE imet.imet_countries SET name_pt='Kiribati' WHERE iso2 = 'KI';
UPDATE imet.imet_countries SET name_pt='São Cristóvão e Nevis' WHERE iso2 = 'KN';
UPDATE imet.imet_countries SET name_pt='Coréia' WHERE iso2 = 'KR';
UPDATE imet.imet_countries SET name_pt='Kuwait' WHERE iso2 = 'KW';
UPDATE imet.imet_countries SET name_pt='Laos' WHERE iso2 = 'LA';
UPDATE imet.imet_countries SET name_pt='Líbano' WHERE iso2 = 'LB';
UPDATE imet.imet_countries SET name_pt='Libéria' WHERE iso2 = 'LR';
UPDATE imet.imet_countries SET name_pt='Líbia' WHERE iso2 = 'LY';
UPDATE imet.imet_countries SET name_pt='Santa Lúcia' WHERE iso2 = 'LC';
UPDATE imet.imet_countries SET name_pt='Liechtenstein' WHERE iso2 = 'LI';
UPDATE imet.imet_countries SET name_pt='Sri Lanka' WHERE iso2 = 'LK';
UPDATE imet.imet_countries SET name_pt='Lesoto' WHERE iso2 = 'LS';
UPDATE imet.imet_countries SET name_pt='Lituânia' WHERE iso2 = 'LT';
UPDATE imet.imet_countries SET name_pt='Luxemburgo' WHERE iso2 = 'LU';
UPDATE imet.imet_countries SET name_pt='Letônia' WHERE iso2 = 'LV';
UPDATE imet.imet_countries SET name_pt='Macau' WHERE iso2 = 'MO';
UPDATE imet.imet_countries SET name_pt='Marrocos' WHERE iso2 = 'MA';
UPDATE imet.imet_countries SET name_pt='Mônaco' WHERE iso2 = 'MC';
UPDATE imet.imet_countries SET name_pt='Moldova' WHERE iso2 = 'MD';
UPDATE imet.imet_countries SET name_pt='Madagáscar' WHERE iso2 = 'MG';
UPDATE imet.imet_countries SET name_pt='Maldivas' WHERE iso2 = 'MV';
UPDATE imet.imet_countries SET name_pt='México' WHERE iso2 = 'MX';
UPDATE imet.imet_countries SET name_pt='Ilhas Marshall' WHERE iso2 = 'MH';
UPDATE imet.imet_countries SET name_pt='Macedônia' WHERE iso2 = 'MK';
UPDATE imet.imet_countries SET name_pt='Mali' WHERE iso2 = 'ML';
UPDATE imet.imet_countries SET name_pt='Malte' WHERE iso2 = 'MT';
UPDATE imet.imet_countries SET name_pt='Mianmar' WHERE iso2 = 'MM';
UPDATE imet.imet_countries SET name_pt='Mongólia' WHERE iso2 = 'MN';
UPDATE imet.imet_countries SET name_pt='Ilhas Marianas do Norte' WHERE iso2 = 'MP';
UPDATE imet.imet_countries SET name_pt='Moçambique' WHERE iso2 = 'MZ';
UPDATE imet.imet_countries SET name_pt='Mauritânia' WHERE iso2 = 'MR';
UPDATE imet.imet_countries SET name_pt='Montserrat' WHERE iso2 = 'MS';
UPDATE imet.imet_countries SET name_pt='Martinica' WHERE iso2 = 'MQ';
UPDATE imet.imet_countries SET name_pt='Mauricio' WHERE iso2 = 'MU';
UPDATE imet.imet_countries SET name_pt='Malawi' WHERE iso2 = 'MW';
UPDATE imet.imet_countries SET name_pt='Malásia' WHERE iso2 = 'MY';
UPDATE imet.imet_countries SET name_pt='Mayote' WHERE iso2 = 'YT';
UPDATE imet.imet_countries SET name_pt='Namibia' WHERE iso2 = 'NA';
UPDATE imet.imet_countries SET name_pt='Nova Caledônia' WHERE iso2 = 'NC';
UPDATE imet.imet_countries SET name_pt='Níger' WHERE iso2 = 'NE';
UPDATE imet.imet_countries SET name_pt='Ilhas Norfolk' WHERE iso2 = 'NF';
UPDATE imet.imet_countries SET name_pt='Nigéria' WHERE iso2 = 'NG';
UPDATE imet.imet_countries SET name_pt='Nicarágua' WHERE iso2 = 'NI';
UPDATE imet.imet_countries SET name_pt='Niue' WHERE iso2 = 'NU';
UPDATE imet.imet_countries SET name_pt='Holanda' WHERE iso2 = 'NL';
UPDATE imet.imet_countries SET name_pt='Noruega' WHERE iso2 = 'NO';
UPDATE imet.imet_countries SET name_pt='Nepal' WHERE iso2 = 'NP';
UPDATE imet.imet_countries SET name_pt='Nauru' WHERE iso2 = 'NR';
UPDATE imet.imet_countries SET name_pt='Nova Zelândia' WHERE iso2 = 'NZ';
UPDATE imet.imet_countries SET name_pt='Omã' WHERE iso2 = 'OM';
UPDATE imet.imet_countries SET name_pt='Paquistão' WHERE iso2 = 'PK';
UPDATE imet.imet_countries SET name_pt='Panamá' WHERE iso2 = 'PA';
UPDATE imet.imet_countries SET name_pt='Pitcairn' WHERE iso2 = 'PN';
UPDATE imet.imet_countries SET name_pt='Peru' WHERE iso2 = 'PE';
UPDATE imet.imet_countries SET name_pt='Filipinas' WHERE iso2 = 'PH';
UPDATE imet.imet_countries SET name_pt='Palau' WHERE iso2 = 'PW';
UPDATE imet.imet_countries SET name_pt='Papua Nova Guiné' WHERE iso2 = 'PG';
UPDATE imet.imet_countries SET name_pt='Polônia' WHERE iso2 = 'PL';
UPDATE imet.imet_countries SET name_pt='Porto Rico' WHERE iso2 = 'PR';
UPDATE imet.imet_countries SET name_pt='Coréia' WHERE iso2 = 'KP';
UPDATE imet.imet_countries SET name_pt='Portugal' WHERE iso2 = 'PT';
UPDATE imet.imet_countries SET name_pt='Paraguai' WHERE iso2 = 'PY';
UPDATE imet.imet_countries SET name_pt='Palestina' WHERE iso2 = 'PS';
UPDATE imet.imet_countries SET name_pt='Polinésia Francesa' WHERE iso2 = 'PF';
UPDATE imet.imet_countries SET name_pt='Catar' WHERE iso2 = 'QA';
UPDATE imet.imet_countries SET name_pt='Reunião' WHERE iso2 = 'RE';
UPDATE imet.imet_countries SET name_pt='Romênia' WHERE iso2 = 'RO';
UPDATE imet.imet_countries SET name_pt='Rússia' WHERE iso2 = 'RU';
UPDATE imet.imet_countries SET name_pt='Ruanda' WHERE iso2 = 'RW';
UPDATE imet.imet_countries SET name_pt='Arábia Saudita' WHERE iso2 = 'SA';
UPDATE imet.imet_countries SET name_pt='Sérvia e Montenegro' WHERE iso2 = 'CS';
UPDATE imet.imet_countries SET name_pt='Sudão' WHERE iso2 = 'SD';
UPDATE imet.imet_countries SET name_pt='Senegal' WHERE iso2 = 'SN';
UPDATE imet.imet_countries SET name_pt='Cingapura' WHERE iso2 = 'SG';
UPDATE imet.imet_countries SET name_pt='Geórgia do Sul e Ilhas Sandwich do Sul' WHERE iso2 = 'GS';
UPDATE imet.imet_countries SET name_pt='Santa Helena' WHERE iso2 = 'SH';
UPDATE imet.imet_countries SET name_pt='Esvalbard e Jan Mayen' WHERE iso2 = 'SJ';
UPDATE imet.imet_countries SET name_pt='Ilhas Salomão' WHERE iso2 = 'SB';
UPDATE imet.imet_countries SET name_pt='Serra Leoa' WHERE iso2 = 'SL';
UPDATE imet.imet_countries SET name_pt='O salvador' WHERE iso2 = 'SV';
UPDATE imet.imet_countries SET name_pt='San Marino' WHERE iso2 = 'SM';
UPDATE imet.imet_countries SET name_pt='Somália' WHERE iso2 = 'SO';
UPDATE imet.imet_countries SET name_pt='“São Pedro e Miquelão”' WHERE iso2 = 'PM';
UPDATE imet.imet_countries SET name_pt='São Tomé e Príncipe' WHERE iso2 = 'ST';
UPDATE imet.imet_countries SET name_pt='Suriname' WHERE iso2 = 'SR';
UPDATE imet.imet_countries SET name_pt='Eslováquia' WHERE iso2 = 'SK';
UPDATE imet.imet_countries SET name_pt='Eslovênia' WHERE iso2 = 'SI';
UPDATE imet.imet_countries SET name_pt='Suécia' WHERE iso2 = 'SE';
UPDATE imet.imet_countries SET name_pt='Suazilândia' WHERE iso2 = 'SZ';
UPDATE imet.imet_countries SET name_pt='Seychelles' WHERE iso2 = 'SC';
UPDATE imet.imet_countries SET name_pt='Síria' WHERE iso2 = 'SY';
UPDATE imet.imet_countries SET name_pt='Ilhas Turcas e Caicos' WHERE iso2 = 'TC';
UPDATE imet.imet_countries SET name_pt='Chade' WHERE iso2 = 'TD';
UPDATE imet.imet_countries SET name_pt='Ir' WHERE iso2 = 'TG';
UPDATE imet.imet_countries SET name_pt='Tailândia' WHERE iso2 = 'TH';
UPDATE imet.imet_countries SET name_pt='Tajiquistão' WHERE iso2 = 'TJ';
UPDATE imet.imet_countries SET name_pt='Toquelau' WHERE iso2 = 'TK';
UPDATE imet.imet_countries SET name_pt='Turmenistão' WHERE iso2 = 'TM';
UPDATE imet.imet_countries SET name_pt='Timor Leste' WHERE iso2 = 'TL';
UPDATE imet.imet_countries SET name_pt='Tongo' WHERE iso2 = 'TO';
UPDATE imet.imet_countries SET name_pt='Trinidad e Tobago' WHERE iso2 = 'TT';
UPDATE imet.imet_countries SET name_pt='Tunísia' WHERE iso2 = 'TN';
UPDATE imet.imet_countries SET name_pt='Peru' WHERE iso2 = 'TR';
UPDATE imet.imet_countries SET name_pt='Tuvalu' WHERE iso2 = 'TV';
UPDATE imet.imet_countries SET name_pt='Taiwan' WHERE iso2 = 'TW';
UPDATE imet.imet_countries SET name_pt='Tanzânia' WHERE iso2 = 'TZ';
UPDATE imet.imet_countries SET name_pt='Uganda' WHERE iso2 = 'UG';
UPDATE imet.imet_countries SET name_pt='Ucrânia' WHERE iso2 = 'UA';
UPDATE imet.imet_countries SET name_pt='Ilhas Distantes dos Estados Unidos' WHERE iso2 = 'UM';
UPDATE imet.imet_countries SET name_pt='Uruguai' WHERE iso2 = 'UY';
UPDATE imet.imet_countries SET name_pt='Estados Unidos' WHERE iso2 = 'US';
UPDATE imet.imet_countries SET name_pt='Uzbequistão' WHERE iso2 = 'UZ';
UPDATE imet.imet_countries SET name_pt='Estado do Vaticano' WHERE iso2 = 'VA';
UPDATE imet.imet_countries SET name_pt='São Vicente e Granadinas' WHERE iso2 = 'VC';
UPDATE imet.imet_countries SET name_pt='Venezuela' WHERE iso2 = 'VE';
UPDATE imet.imet_countries SET name_pt='Ilhas Virgens Britânicas' WHERE iso2 = 'VG';
UPDATE imet.imet_countries SET name_pt='Ilhas Virgens Americanas' WHERE iso2 = 'VI';
UPDATE imet.imet_countries SET name_pt='Vietnã' WHERE iso2 = 'VN';
UPDATE imet.imet_countries SET name_pt='Vanuatu' WHERE iso2 = 'VU';
UPDATE imet.imet_countries SET name_pt='Wallis e Futuna' WHERE iso2 = 'WF';
UPDATE imet.imet_countries SET name_pt='Samoa' WHERE iso2 = 'WS';
UPDATE imet.imet_countries SET name_pt='Iémen' WHERE iso2 = 'YE';
UPDATE imet.imet_countries SET name_pt='África do Sul' WHERE iso2 = 'ZA';
UPDATE imet.imet_countries SET name_pt='Zâmbia' WHERE iso2 = 'ZM';
UPDATE imet.imet_countries SET name_pt='Zimbábue' WHERE iso2 = 'ZW';

COMMIT;