BEGIN;

INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('AFN', 'Afghani', 'Afghani');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('BOV', 'Mvdol', 'Mvdol');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('BTN', 'Ngultrum', 'Ngultrum');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('CHE', 'Euro WIR', 'WIR Euro');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('CHW', 'Franc WIR', 'WIR Franc');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('CLF', 'Unidades de fomento', 'Unidades de fomento');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('COU', 'Unidad de Valor Real', 'Unidad de Valor Real');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('CUC', 'Peso Convertible', 'Peso Convertible');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('LSL', 'Loti', 'Loti');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('MXV', 'Mexican Unidad de Inversion (UDI)', 'Mexican Unidad de Inversion (UDI)');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('NAD', 'Dollar de Namibie', 'Namibia Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('SSP', 'Livre de Soudan du Sud', 'South Sudanese Pound');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('TMT', 'Manat (nouveau)', 'Turkmenistan New Manat');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('UYU', 'Peso Uruguayo', 'Peso Uruguayo');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('ZAR', 'Rand (Dollar namibien)', 'Rand');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('ALL', 'Lek', 'Lek');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('DZD', 'Dinar algérien', 'Algerian Dinar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('EUR', 'Euro', 'Euro');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('AOA', 'Kwanza', 'Kwanza');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('XCD', 'Dollar des Caraïbes orientales', 'East Caribbean Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('ANG', 'Florin des Antilles', 'Netherlands Antillean Guilder');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('SAR', 'Riyal saoudien', 'Saudi Riyal');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('ARS', 'Peso argentin', 'Argentine Peso');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('AMD', 'Dram arménien', 'Armenian Dram');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('AWG', 'Florin d''Aruba', 'Aruban Florin');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('AUD', 'Dollar australien', 'Australian Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('AZN', 'Manat', 'Azerbaijanian Manat');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('BSD', 'Dollar des Bahamas', 'Bahamian Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('BHD', 'Dinar de Bahreïn', 'Bahraini Dinar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('BDT', 'Taka', 'Taka');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('BBD', 'Dollar de Barbade', 'Barbados Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('BYR', 'Rouble bélorusse', 'Belarussian Ruble');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('BZD', 'Dollar de Belize', 'Belize Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('XOF', 'Franc CFA de l''Afrique de l''Ouest (BCEAO - UEMOA)', 'CFA Franc BCEAO');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('BMD', 'Dollar des Bermudes', 'Bermudian Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('INR', 'Roupie indienne', 'Indian Rupee');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('BAM', 'Mark convertible', 'Convertible Mark');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('BWP', 'Pula', 'Pula');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('NOK', 'Couronne norvégienne', 'Norwegian Krone');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('BRL', 'Real de Brésil', 'Brazilian Real');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('BND', 'Dollar de Brunei', 'Brunei Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('BGN', 'Lev de Bulgarie', 'Bulgarian Lev');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('KYD', 'Dollar des Iles Caïmanes', 'Cayman Islands Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('KHR', 'Riel', 'Riel');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('CAD', 'Dollar canadien', 'Canadian Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('CVE', 'Escudo du Cap-Vert', 'Cape Verde Escudo');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('CLP', 'Peso chilien (Unité d''investissement)', 'Chilean Peso');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('CNY', 'Yuan Ren-Min-Bi', 'Yuan Renminbi');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('COP', 'Peso colombien (Unidad de Valor Real)', 'Colombian Peso');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('KMF', 'Franc des Comores', 'Comoro Franc');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('CDF', 'Franc Congolais', 'Congolese Franc');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('NZD', 'Dollar néo-zélandais', 'New Zealand Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('KRW', 'Won', 'Won');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('KPW', 'Won de la Corée du Nord', 'North Korean Won');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('CRC', 'Colon de Costa Rica', 'Costa Rican Colon');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('HRK', 'Kuna', 'Croatian Kuna');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('CUP', 'Peso cubain', 'Cuban Peso');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('DKK', 'Couronne danoise', 'Danish Krone');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('DJF', 'Franc de Djibouti', 'Djibouti Franc');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('DOP', 'Peso dominicain', 'Dominican Peso');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('EGP', 'Livre égyptienne', 'Egyptian Pound');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('SVC', 'Colon du El Salvador (Dollar des États-Unis)', 'El Salvador Colon');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('AED', 'Dirham des émirats arabes unis', 'UAE Dirham');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('ERN', 'Nakfa', 'Nakfa');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('ETB', 'Birr éthiopien', 'Ethiopian Birr');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('FKP', 'Livre de Falkland', 'Falkland Islands Pound');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('FJD', 'Dollar de Fidji', 'Fiji Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('XDR', 'Droit de tirage spécial (D.T.S.)', 'SDR (Special Drawing Right)');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('GMD', 'Dalasi', 'Dalasi');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('GEL', 'Lari', 'Lari');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('GHS', 'Ghana Cedi', 'Ghana Cedi');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('GIP', 'Livre de Gibraltar', 'Gibraltar Pound');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('GTQ', 'Quetzal', 'Quetzal');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('GBP', 'Livre sterling', 'Pound Sterling');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('GNF', 'Franc guinéen', 'Guinea Franc');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('GYD', 'Dollar de Guyane', 'Guyana Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('HTG', 'Gourde (Dollar des États-Unis)', 'Gourde');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('HNL', 'Lempira', 'Lempira');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('HKD', 'Dollar de Hong-Kong', 'Hong Kong Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('HUF', 'Forint', 'Forint');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('IDR', 'Rupiah', 'Rupiah');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('IRR', 'Rial iranien', 'Iranian Rial');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('IQD', 'Dinar iraquien', 'Iraqi Dinar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('ISK', 'Couronne islandaise', 'Iceland Krona');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('ILS', 'Nouvel israëli sheqel', 'New Israeli Sheqel');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('JMD', 'Dollar jamaïcain', 'Jamaican Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('JPY', 'Yen', 'Yen');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('JOD', 'Dinar jordanien', 'Jordanian Dinar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('KZT', 'Tenge', 'Tenge');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('KES', 'Shilling du Kenya', 'Kenyan Shilling');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('KGS', 'Som', 'Som');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('KWD', 'Dinar koweïtien', 'Kuwaiti Dinar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('LAK', 'Kip', 'Kip');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('LVL', 'Lats letton', 'Latvian Lats');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('LBP', 'Livre libanaise', 'Lebanese Pound');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('LRD', 'Dollar libérien', 'Liberian Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('LYD', 'Dinar libyen', 'Libyan Dinar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('CHF', 'Franc Suisse', 'Swiss Franc');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('LTL', 'Litas lituanien', 'Lithuanian Litas');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('MOP', 'Pataca', 'Pataca');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('MKD', 'Denar', 'Denar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('MGA', 'Malagasy Ariary', 'Malagasy Ariary');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('MYR', 'Ringgit de Malaisie', 'Malaysian Ringgit');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('MWK', 'Kwacha de Malawi', 'Kwacha');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('MVR', 'Rufiyaa', 'Rufiyaa');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('MAD', 'Dirham marocain', 'Moroccan Dirham');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('MUR', 'Roupie de Maurice', 'Mauritius Rupee');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('MRO', 'Ouguija', 'Ouguiya');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('MXN', 'Peso mexicain (Mexican Unidad de Inversion - UDI)', 'Mexican Peso');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('MDL', 'Leu de Moldovie', 'Moldovan Leu');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('MNT', 'Tugrik', 'Tugrik');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('MZN', 'Metical', 'Mozambique Metical');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('MMK', 'Kyat', 'Kyat');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('NPR', 'Roupie du Népal', 'Nepalese Rupee');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('NIO', 'Cordoba Oro', 'Cordoba Oro');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('NGN', 'Naira', 'Naira');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('XPF', 'Franc CFP', 'CFP Franc');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('OMR', 'Rial Omani', 'Rial Omani');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('BOB', 'Boliviano', 'Boliviano');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('ZWL', 'Dollar de Zimbabwe', 'Zimbabwe Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('ZMW', 'Kwacha', 'Zambian Kwacha');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('USD', 'US Dollar', 'US Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('BIF', 'Franc Burundais', 'Burundi Franc');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('XAF', 'Franc CFA de l''Afrique centrale (BEAC - CEMAC)', 'CFA Franc BEAC');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('UGX', 'Nouveau Shilling ougandais', 'Uganda Shilling');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('UZS', 'Soum d''Ouzbékistan', 'Uzbekistan Sum');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('PKR', 'Roupie du Pakistan', 'Pakistan Rupee');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('PAB', 'Balboa (Dollar des États-Unis)', 'Balboa');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('PGK', 'Kina', 'Kina');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('PYG', 'Guarani', 'Guarani');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('PEN', 'Nouveau Sol', 'Nuevo Sol');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('PHP', 'Peso philippin', 'Philippine Peso');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('PLN', 'Zloty', 'Zloty');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('QAR', 'Riyal du Qatar', 'Qatari Rial');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('RON', 'Nouveau Leu', 'New Romanian Leu');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('RUB', 'Rouble russe', 'Russian Ruble');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('SHP', 'Livre de Sainte-Hélène', 'Saint Helena Pound');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('SBD', 'Dollar de Salomon', 'Solomon Islands Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('WST', 'Tala', 'Tala');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('STD', 'Dobra', 'Dobra');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('RSD', 'Dinar de Serbie', 'Serbian Dinar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('SCR', 'Roupie des Seychelles', 'Seychelles Rupee');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('SLL', 'Leone', 'Leone');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('SGD', 'Dollar de Singapour', 'Singapore Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('SOS', 'Shilling de Somalie', 'Somali Shilling');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('SDG', 'Livre soudanaise', 'Sudanese Pound');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('LKR', 'Roupie de Sri Lanka', 'Sri Lanka Rupee');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('SEK', 'Couronne suédoise', 'Swedish Krona');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('SRD', 'Dollar de Suriname', 'Surinam Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('SZL', 'Lilangeni', 'Lilangeni');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('SYP', 'Livre syrienne', 'Syrian Pound');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('TJS', 'Somoni', 'Somoni');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('TWD', 'Nouveau dollar de Taïwan', 'New Taiwan Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('TZS', 'Shilling de Tanzanie', 'Tanzanian Shilling');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('CZK', 'Couronne tchèque', 'Czech Koruna');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('THB', 'Baht', 'Baht');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('TOP', 'Pa''anga', 'Pa''anga');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('TTD', 'Dollar de la Trinité et de Tobago', 'Trinidad and Tobago Dollar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('TND', 'Dinar tunisien', 'Tunisian Dinar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('TRY', 'Nouvelle Livre', 'Turkish Lira');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('UAH', 'Hryvnia', 'Hryvnia');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('UYI', 'Peso uruguayen', 'Uruguay Peso en Unidades Indexadas (URUIURUI)');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('VUV', 'Vatu', 'Vatu');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('VEF', 'Bolivar Fuerte', 'Bolivar');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('VND', 'Dong', 'Dong');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('YER', 'Riyal du Yémen', 'Yemeni Rial');
INSERT into imet.imet_currencies (iso, name_fr, name_en) VALUES ('RWF', 'Franc Rwandais', 'Rwanda Franc');

COMMIT;