BEGIN;

-- #### Central Africa ####
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_294', 'COD', '20324', 'Bili-Uere', 'VI', '1974-03-12');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_295', 'COD', '5183', 'Bombo Lumene', 'VI', '1968-02-10');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_296', 'COD', '555512073', 'Bomu', 'Ib', '1974-02-14');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_297', 'COD', '20337', 'Bushimaie', 'VI', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_299', 'COD', '20327', 'Gangala-na-Bodio', 'VI', '1974-02-14');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_300', 'COD', '1083', 'Garamba', 'II', '1938-03-17');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_301', 'COD', '1082', 'Kahuzi-Biega', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_302', 'COD', '350001', 'Kisimba Ikobo', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_304', 'COD', '1084', 'Kundelungu', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_305', 'COD', '555512076', 'Tumba-Lediima', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_306', 'COD', '555512077', 'Lomako-Yokokala', 'Not Reported', '2006-06-28');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_307', 'COD', '555625665', 'Lomami National Park', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_311', 'COD', '555512067', 'Lubudi-Sampwe', 'VI', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_313', 'COD', '555512071', 'Luki', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_314', 'COD', '72340', 'Luo Scientific Reserve', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_316', 'COD', '20330', 'Maika-Penge', 'VI', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_317', 'COD', '1080', 'Maiko', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_319', 'COD', '72312', 'Itombwe', 'Not Reported', '2006-10-11');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_323', 'COD', '478028', 'Ngiri', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_324', 'COD', '37043', 'Okapis', 'II', '1992-05-02');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_327', 'COD', '29685', 'Rubi-Tele', 'VI', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_328', 'COD', '20331', 'Rutshuru', 'VI', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_329', 'COD', '10906', 'Salonga National Park', 'Not Applicable', '1970-12-31');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_330', 'COD', '354001', 'Sankuru', 'Not Reported', '2007-11-06');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_332', 'COD', '20334', 'Swa-Kibula', 'VI', '1952-12-31');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_333', 'COD', '317056', 'Tayna', 'Not Reported', '2006-04-03');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_334', 'COD', '1079', 'Upemba', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_337', 'COD', '2017', 'Virunga National Park', 'Not Applicable', '1925-04-21');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_338', 'COD', '555512072', 'Yangambi', 'Ia', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_339', 'CAF', '639', 'Bamingui-Bangoran', 'II', '1933-12-31');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_340', 'CAF', '1249', 'Vassako-Bolo', 'Ia', '1933-12-31');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_341', 'CAF', '2256', 'Manovo-Gounda-Saint Floris', 'II', '1933-12-31');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_342', 'CAF', '2257', 'Avakaba Presidential Park', 'IV', '1968-08-31');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_343', 'CAF', '2258', 'Andre Felix', 'II', '1940-01-01');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_344', 'CAF', '2259', 'Zemongo', 'IV', '1925-12-31');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_345', 'CAF', '2260', 'Ouandjia-Vakaga', 'IV', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_346', 'CAF', '2261', 'Yata-Ngaya', 'IV', '1940-12-31');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_347', 'CAF', '2262', 'Gribingui-Bamingui', 'IV', '1933-01-01');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_348', 'CAF', '2264', 'Nana-Barya', 'IV', '1953-12-11');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_349', 'CAF', '2265', 'Koukourou-Bamingui', 'IV', '1933-10-12');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_351', 'CAF', '28741', 'Botambi', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_352', 'CAF', '28745', 'Ngotto', 'Not Reported', '1951-02-09');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_353', 'CAF', '31458', 'Dzanga-Ndoki', 'II', '1984-07-24');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_354', 'CAF', '31459', 'Dzanga-Sangha', 'VI', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_361', 'CAF', '317281', 'Mbaéré-Bodingué', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_362', 'GAB', '666', 'Wonga-Wongué', 'Not Reported', '1976-04-08');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_364', 'GAB', '28840', 'Ouanga Plain', 'Not Reported', '1966-12-29');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_365', 'GAB', '28844', 'Ngove-Ndogo', 'IV', '1966-12-29');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_366', 'GAB', '28845', 'Sette-Cama', 'Not Reported', '1966-12-29');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_368', 'GAB', '28847', 'Moukalaba', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_370', 'GAB', '72320', 'Akanda', 'Not Reported', '2002-08-30');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_371', 'GAB', '72324', 'Minkebe', 'Not Reported', '2002-08-30');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_374', 'GAB', '303872', 'Monts Birougou', 'Not Reported', '2002-08-30');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_375', 'GAB', '303873', 'Ivindo', 'Not Reported', '2002-08-30');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_376', 'GAB', '303874', 'Loango', 'Not Reported', '2002-08-30');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_377', 'GAB', '303875', 'Lopé', 'Not Reported', '2002-08-30');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_378', 'GAB', '303877', 'Moukalaba-Doudou', 'Not Reported', '2002-08-30');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_379', 'GAB', '303878', 'Mwagné', 'Not Reported', '2002-08-30');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_380', 'GAB', '303879', 'Pongara', 'Not Reported', '2002-08-30');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_381', 'GAB', '303880', 'Waka', 'Not Reported', '2002-08-30');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_382', 'GAB', '306235', 'Plateaux Batéké', 'Not Reported', '2002-08-30');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_383', 'GAB', '306237', 'Monts de Cristal', 'Not Reported', '2002-08-30');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_384', 'CMR', '606', 'Bouba Ndjida', 'II', '1968-12-05');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_385', 'CMR', '607', 'Bénoué', 'II', '1968-12-05');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_386', 'CMR', '608', 'Waza', 'II', '1968-01-01');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_387', 'CMR', '609', 'Kalamaloué', 'II', '1972-12-31');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_388', 'CMR', '610', 'Mozogo Gokoro', 'II', '1972-01-01');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_389', 'CMR', '1240', 'Dja', 'IV', '1950-04-25');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_390', 'CMR', '1241', 'Faro', 'II', '1980-12-05');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_391', 'CMR', '1242', 'Campo-Ma''an', 'II', '2000-01-06');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_392', 'CMR', '1244', 'Douala Edéa', 'IV', '1932-12-31');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_393', 'CMR', '1245', 'Lobéké', 'II', '2001-03-19');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_394', 'CMR', '146627', 'Kimbi-Fungom', 'II', '1964-01-01');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_396', 'CMR', '1628', 'Lac Ossa', 'IV', '1948-12-31');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_397', 'CMR', '20058', 'Korup', 'II', '1986-12-01');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_399', 'CMR', '20112', 'Bayang-Mbo', 'IV', '1996-03-12');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_400', 'CMR', '20117', 'Rumpi Hills', 'IV', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_401', 'CMR', '20125', 'Santchou', 'IV', '1964-12-31');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_402', 'CMR', '20166', 'Mbam et Djerem', 'II', '2000-01-06');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_403', 'CMR', '30674', 'Nki', 'II', '2005-10-06');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_413', 'CMR', '308624', 'Boumba Bek', 'II', '2005-10-06');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_417', 'CMR', '555548871', 'Tchabal Mbabo', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_423', 'CMR', '308634', 'Ndongere', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_425', 'CMR', '308636', 'Mengame', 'IV', '2008-07-14');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_426', 'CMR', '308637', 'Vallée du Mbéré', 'II', '2004-02-04');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_434', 'CMR', '354004', 'Kagwene', 'IV', '2008-04-03');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_435', 'COG', '643', 'Odzala Kokoua', 'II', '2005-05-10');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_436', 'COG', '2266', 'Léfini', 'IV', '1951-11-26');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_437', 'COG', '2270', 'Tsoulou', 'IV', '1963-01-07');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_438', 'COD', '37044', 'Mangrove Nature Reserve or Marine Park', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_439', 'COG', '72332', 'Nouabalé-Ndoki', 'II', '1993-12-31');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_440', 'COG', '99855', 'Tchimpounga', 'IV', '1999-12-31');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_441', 'COG', '99862', 'Lessio-Louna', 'IV', '2009-07-20');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_442', 'COG', '300342', 'Lossi', 'IV', '2001-05-10');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_443', 'COG', '313401', 'Conkouati-Douli', 'II', '1999-08-11');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_444', 'COG', '313494', 'Lac Télé', 'IV', '2001-05-10');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_446', 'GNQ', '313354', 'Caldera de Luba', 'Ib', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_447', 'GNQ', '313355', 'Playa Nendyi', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_448', 'GNQ', '313359', 'Piedra Bere', 'III', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_449', 'GNQ', '313360', 'Piedra Nzas', 'III', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_450', 'GNQ', '313361', 'Rio Campo', 'IV', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_451', 'GNQ', '313362', 'Punta Llende', 'IV', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_452', 'GNQ', '313364', 'Corisco y Elobeyes', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_453', 'GNQ', '20260', 'Estuario del Muni', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_454', 'GNQ', '20264', 'Pico de Basilé', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_455', 'GNQ', '20267', 'Monte Alén', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_456', 'GNQ', '20268', 'Altos de Nsork', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_457', 'GNQ', '20269', 'Annobón', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_458', 'GNQ', '313366', 'Monte Temelón', 'IV', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_459', 'BDI', '9160', 'Ruvubu', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_460', 'BDI', '9161', 'Kibira', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_461', 'BDI', '9162', 'Rusizi', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_463', 'BDI', '9164', 'Bururi Forest', 'Ib', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_464', 'BDI', '9165', 'Rumonge', 'Ib', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_465', 'BDI', '9166', 'Kigwena Forest', 'Ib', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_466', 'TCD', '641', 'Zakouma', 'II', '1963-05-07');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_467', 'TCD', '642', 'Manda', 'II', '1965-03-19');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_468', 'TCD', '1250', 'Ouadi Rimé-Ouadi Achim', 'IV', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_469', 'TCD', '5164', 'Bahr Salamat', 'IV', '1964-02-29');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_470', 'TCD', '5165', 'Siniaka-Minia', 'IV', '1961-05-17');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_471', 'TCD', '5166', 'Mandelia', 'IV', '1967-10-07');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_472', 'TCD', '5168', 'Binder-Léré', 'IV', '1974-04-24');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_474', 'TCD', '9034', 'Abou Telfane', 'IV', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_475', 'RWA', '862', 'Akagera', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_476', 'RWA', '863', 'Volcans', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_477', 'RWA', '9148', 'Nyungwe', 'IV', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_478', 'RWA', '21416', 'Gishwati', 'IV', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_479', 'RWA', '21417', 'Mukura', 'IV', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_480', 'STP', '555592842', 'Parque Natural Obô do Príncipe', 'Not Assigned', '2006-12-31');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_481', 'STP', '124355', 'Parque Natural Obô de São Tomé', 'Not Assigned', '2006-12-31');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_483', 'CMR', '555547995', 'Deng Deng', 'II', '2010-03-18');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_484', 'CMR', '478190', 'Kilum Ijim, Mont Oku', 'IV', '2004-12-08');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_485', 'CMR', '555547997', 'Kom', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_486', 'CMR', '555548000', 'Mefou', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_487', 'CMR', '555547994', 'Mont Cameroun', 'II', '2009-12-18');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_489', 'CAF', '2059', 'Basse-Lobaye', 'Not Applicable', '1951-01-01');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_490', 'COG', '13694', 'Réserve de biosphère de la Dimonika', 'Not Applicable', '1988-03-01');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_491', 'COG', '555571319', 'Mont Fouari', 'IV', '1958-02-08');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_492', 'COG', '555571316', 'Mont Mavoumbou', 'Not Reported', '1956-02-08');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_493', 'COG', '555571317', 'Ngyanga Nord', 'IV', '1910-01-15');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_494', 'COG', '555571318', 'Ngyanga Sud', 'Not Reported', '1956-02-08');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_497', 'COD', '555512065', 'Luama-Katanga', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_503', 'COD', '555512068', 'N''Sele', 'Not Reported', '1983-05-03');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_504', 'COD', '555512070', 'Lufira', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_507', 'COD', '555512075', 'Lac Tshangalele', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_509', 'GAB', '301850', 'Mayumba', 'Not Reported', '2002-08-30');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_551', 'BDI', '9167', 'Faille de Nyakazu', 'III', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_553', 'BDI', '9168', 'Chutes de Karera', 'III', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_554', 'BDI', '61707', 'Gisagara', 'V', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_565', 'CMR', '555548873', 'Manyange na Elombo-Campo', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_574', 'CMR', '555548872', 'Ma Mbed Mbed', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_604', 'CMR', '555547993', 'Mpem et Djim', 'II', '2004-05-12');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_612', 'CMR', '555547996', 'Takamanda', 'II', '2008-11-21');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_614', 'CMR', '555547998', 'Bakossi', 'II', '2007-11-28');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_617', 'CMR', '555548870', 'Ebo', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_664', 'COD', '555512066', 'Luama-Kivu', 'VI', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_679', 'COG', '354010', 'Ntokou-Pikounda', 'Not Reported', '2013-03-04');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_695', 'TCD', '555558303', 'Aouk', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_709', 'CMR', '555622119', 'Ngoyla', 'IV', '2014-08-27');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_710', 'CMR', '555622120', 'Tofala Hill', 'IV', '2014-09-29');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_712', 'COD', '555555524', 'Lyondji Bonobo Community Reserve', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_714', 'TCD', '555558302', 'Sena Oura', 'II', '2010-06-10');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_731', 'GAB', '28846', 'Iguela', 'IV', '1966-12-29');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_741', 'COD', '301834', 'Abumonbazi', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_754', 'COG', '555571320', 'Léfini', 'Not Reported', '1963-01-07');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_756', 'BDI', '101434', 'Vyanda', 'Ib', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_757', 'BDI', '101433', 'Réserve de Muyange', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_758', 'TCD', '555622048', 'Ennedi Natural and Cultural Reserve', 'Not Applicable', '1899-12-30');
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_771', 'RWA', '5190', 'Parc national des Volcans', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_772', 'BDI', '555622053', 'Réserve de Nkayamba', 'Ib', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_773', 'COG', '109020', 'Libenga', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_774', 'GAB', '555624882', 'Reserve Aquatique des Canyons du Cap Lopez', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_775', 'GAB', '555624904', 'Zone Tampon Parc Marin de l''Ile Mbanie', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_776', 'GAB', '166788', 'Monts Doudou', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_777', 'BDI', '28464', 'Monge Forest', 'Ib', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_778', 'COG', '555555584', 'Site Ramsar Ntokou-Pikounda', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_779', 'COG', '555626098', 'Leketi-Mbama', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_780', 'BDI', '555558379', 'Parc National de la Ruvubu', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_781', 'BDI', '317142', 'Mukungu-Rukamabasi', 'V', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_782', 'STP', '555592849', 'Zona Tampão do Parque Natural Obô do Príncipe', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_783', 'TCD', '902874', 'Plaines d''inondation des Bahr Aouk et Salamat', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_784', 'TCD', '555547987', 'Lakes of Ounianga', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_785', 'GAB', '555624883', 'Parc Marin de l''embouchure de la Nyanga', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_786', 'GNQ', '901295', 'Río Ntem o Campo', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_787', 'COG', '7425', 'Parc national d''Odzala', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_788', 'GAB', '109035', 'Chutes et Rapides sur Ivindo', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_789', 'GAB', '555624896', 'Parc Marin de l''embouchure d''Iguela', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_790', 'CMR', '555555587', 'Partie Camerounaise du Fleuve Ntem', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_791', 'GAB', '903129', 'Ecosystem and Relict Cultural Landscape of Lopé-Okanda', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_792', 'BDI', '555558381', 'Paysage Aquatique Protégé du Nord', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_793', 'GAB', '555624901', 'Zone Tampon Parc Marin de l''embouchure d''Ozouri', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_794', 'GAB', '555624888', 'Reserve Aquatique du Delta de l''Ogooue', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_795', 'GAB', '555624878', 'Reserve Aquatique de Mandji-Etimboue', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_796', 'COG;CMR;CAF', '555547988', 'Sangha Trinational', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_797', 'RWA', '101182', 'Nyabarongo River Wetlands', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_798', 'GAB', '555624879', 'Parc Marin de l''embouchure d''Olende', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_799', 'COG', '555555585', 'Site Ramsar Odzala Kokoua', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_800', 'GAB', '109034', 'Bas Ogooue', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_801', 'RWA', '101179', 'Akanyaru wetlands', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_802', 'GAB', '555624894', 'Reserve Aquatique d''Olowi', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_803', 'COD', '555512074', 'Mangai', 'VI', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_804', 'GAB', '555624884', 'Reserve Aquatique du Grand Sud du Gabon', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_805', 'TCD', '14086', 'Larmanaye', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_806', 'GAB', '28848', 'Moukalaba-Dougoua', 'IV', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_807', 'CAF', '301830', 'Zone Pilote de la Sangba', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_808', 'CAF', '301832', 'Kaga Bandoro', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_809', 'GAB', '555624890', 'Parc Marin de l''embouchure d''Ozouri', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_810', 'CAF', '9022', 'Bongo', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_811', 'BDI', '555622055', 'Lacs du Nord', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_812', 'TCD', '902837', 'Plaines d''inondation du Logone et les dépressions Toupouri', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_813', 'GAB', '555624898', 'Zone Tampon Parc Marin de l''embouchure d''Olende', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_814', 'GAB', '555624893', 'Reserve Aquatique de Tchatamba', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_815', 'GAB', '28839', 'Petit Loango', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_816', 'CAF', '301831', 'Kotto', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_817', 'GAB', '555624885', 'Reserve Aquatique de Koumandji', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_818', 'CMR', '902869', 'Waza Logone Floodplain', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_819', 'CMR', '3011', 'Benoué', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_820', 'GAB', '555624880', 'Parc Marin de la Pointe Denis', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_821', 'CAF', '301877', 'Ngotto extension', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_822', 'RWA', '109095', 'Rugezi-Bulera-Ruhondo', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_823', 'BDI', '555622054', 'Forêt de Murehe', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_824', 'CAF', '146632', 'Bangassou', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_825', 'GAB', '903026', 'Parc National Pongara', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_826', 'COD', '166888', 'Parc national des Mangroves', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_827', 'CAF', '902803', 'Les Rivières de Mbaéré-Bodingué', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_828', 'TCD', '14085', 'Goz-Beida', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_829', 'CAF', '28754', 'Banzoum', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_830', 'COG', '555629210', 'Bas-Kouilou-Yombo', 'IV', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_831', 'CAF', '2060', 'Bamingui-Bangoran Conservation Area', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_832', 'TCD', '902838', 'Réserve de faune de Binder-Léré', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_833', 'RWA', '101181', 'Rugezi Marsh', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_834', 'GNQ', '901293', 'Isla de Annobón', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_835', 'COG', '166739', 'Réserve Communautaire du Lac Télé/Likouala-aux-Herbes', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_836', 'COD', '4328', 'Kahuzi-Biega National Park', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_837', 'CAF', '301833', 'Nana', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_838', 'CAF', '100877', 'Mbissa', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_839', 'COD', '555512069', 'Parc Marin des Mangroves', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_840', 'COG', '109017', 'Cayo-Loufoualeba', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_841', 'STP', '555592850', 'Zona Tampão do Parque Natural Obô de São Tomé', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_842', 'COD', '2172', 'Yangambi', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_843', 'COG', '109018', 'Conkouati-Douli', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_844', 'COG', '478033', 'Sangha-Nouabalé-Ndoki', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_845', 'COD', '555512064', 'Bomu', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_846', 'GAB', '555624902', 'Zone Tampon Parc Marin de l''embouchure de la Banio', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_847', 'GAB', '555624905', 'Zone Tampon Parc Marin de l''embouchure d''Iguela', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_848', 'GAB', '67931', 'Wongha-Wonghé', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_849', 'GAB', '555624900', 'Zone Tampon Parc Marin du Cap Lopez', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_850', 'CMR', '902990', 'Barombi Mbo Crater Lake', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_851', 'GAB', '555624906', 'Zone Tampon Parc Marin de l''embouchure de Nyanga', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_852', 'COD', '555625801', 'Bassin de la Lufira', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_853', 'CMR', '555542688', 'Estuaire du Rio Del Rey', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_854', 'GAB', '555624889', 'Parc Marin du Cap Lopez', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_855', 'GNQ', '901294', 'Reserva Natural del Estuario del Muni', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_856', 'CAF', '28752', 'Loumi', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_857', 'CAF', '555542690', 'Riviere Sangha située en République Centrafricaine', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_858', 'CAF', '100876', 'ECOFAC Project in Ngotto Forest', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_859', 'CAF', '16792', 'Manovo-Gounda St Floris National Park', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_860', 'GAB', '555624891', 'Parc Marin de l''embouchure de la Banio', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_861', 'BDI', '555558380', 'Réserve Naturelle de la Malagarazi', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_862', 'BDI', '317143', 'Mabanda/Nyanza-Lake', 'V', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_863', 'CMR', '17758', 'Dja Faunal Reserve', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_864', 'CMR', '2056', 'Waza', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_865', 'COD', '4327', 'Garamba National Park', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_866', 'COD', '5087', 'Vallée de la Lufira', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_867', 'CMR', '3012', 'Dja', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_868', 'GAB', '555624897', 'Parc Marin de l''embouchure de Sette Cama', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_869', 'CAF', '28750', 'Batangafo', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_870', 'GAB', '555624895', 'Reserve Aquatique du Cap Esterias', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_871', 'COG', '354009', 'Patte d''Oie', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_872', 'GAB', '903027', 'Site Ramsar des Monts Birougou', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_873', 'GAB', '5187', 'Réserve naturelle intégrale d''Ipassa-Makokou', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_874', 'GAB', '555624899', 'Zone Tampon Parc Marin de la Pointe Denis', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_875', 'STP', '902976', 'Ilhas Tinhosas', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_876', 'COG', '555626099', 'Tchicapika-Owando', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_877', 'COG', '478032', 'Les Rapides du Congo-Djoué', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_878', 'COD', '9143', 'Réserve forestière de Luki', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_879', 'COD', '478291', 'Parc national des Virunga', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_880', 'COG', '109019', 'Grands affluents', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_881', 'GAB', '109036', 'Rapides de Mboungou Badouma et de Doume', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_882', 'CAF', '2555', 'Aouk-Aoukale', 'IV', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_883', 'GAB', '555624903', 'Zone Tampon Parc Marin de l''embouchure Sette-Cama', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_884', 'TCD', '109008', 'Plaine de Massenya', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_885', 'COD', '166889', 'Virunga', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_886', 'CMR', '555555588', 'Zone Humide d''Ebogo', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_887', 'GAB', '555624892', 'Reserve Aquatique du Caillou', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_888', 'TCD', '900672', 'Partie tchadienne du lac Tchad', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_889', 'TCD', '14084', 'Beinamar', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_890', 'GAB', '555624887', 'Reserve Aquatique de l''Abysse Bleu', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_891', 'GAB', '555624886', 'Parc Marin de l''Ile Mbanie', 'Not Assigned', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_892', 'BDI', '900788', 'Parc National de la Rusizi', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_893', 'CAF', '100878', 'Batouri sapoua', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_894', 'COG', '555555586', 'Site Ramsar Vallée du Niari', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_895', 'COD', '555626064', 'Réserve du triangle de la Ngiri', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_896', 'CMR', '555542689', 'Partie Camerounaise du Lac Tchad', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_897', 'COG', '555626097', 'Loubetsi-Nyanga', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_898', 'STP', '555592851', 'The Island of Príncipe', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_899', 'COD', '478292', 'Salonga', 'II', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_900', 'CMR', '903089', 'Partie camerounaise du fleuve Sangha', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_901', 'COD', '124389', 'Okapis Wildlife Reserve', 'Not Applicable', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_902', 'CAF', '28778', 'Birini', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_903', 'TCD', '30017', 'Lac Fitri', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_904', 'GAB', '67933', 'Setté Cama', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_905', 'GAB', '903025', 'Parc National Akanda', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_906', 'CAF', '28753', 'Ouabere', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_907', 'GAB', '67932', 'Petit Loango', 'Not Reported', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_908', 'TCD', '9033', 'Fada Archei', 'IV', NULL);
INSERT into imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('OFAC_909', 'GAB', '555624881', 'Reserve Aquatique de Gamba', 'Not Assigned', NULL);

COMMIT;