BEGIN;

INSERT into imet.imet_countries VALUES ('AF', 'AFG', 4, 'Afghanistan', 'Afghanistan', 'Afganistán');
INSERT into imet.imet_countries VALUES ('ZA', 'ZAF', 710, 'Afrique du Sud', 'South Africa', 'Sudáfrica');
INSERT into imet.imet_countries VALUES ('AL', 'ALB', 8, 'Albanie', 'Albania', 'Albania');
INSERT into imet.imet_countries VALUES ('DZ', 'DZA', 12, 'Algérie', 'Algeria', 'Argelia');
INSERT into imet.imet_countries VALUES ('DE', 'DEU', 276, 'Allemagne', 'Germany', 'Alemania');
INSERT into imet.imet_countries VALUES ('AD', 'AND', 20, 'Andorre', 'Andorra', 'Andorra');
INSERT into imet.imet_countries VALUES ('AO', 'AGO', 24, 'Angola', 'Angola', 'Angola');
INSERT into imet.imet_countries VALUES ('AI', 'AIA', 660, 'Anguilla', 'Anguilla', 'Anguilla');
INSERT into imet.imet_countries VALUES ('AQ', 'ATA', 10, 'Antarctique', 'Antarctica', 'Antartida');
INSERT into imet.imet_countries VALUES ('AG', 'ATG', 28, 'Antigua-et-Barbuda', 'Antigua and Barbuda', 'Antigua y Barbuda');
INSERT into imet.imet_countries VALUES ('AN', 'ANT', 530, 'Antilles Néerlandaises', 'Netherlands Antilles', 'Antillas Holandesas');
INSERT into imet.imet_countries VALUES ('SA', 'SAU', 682, 'Arabie Saoudite', 'Saudi Arabia', 'Arabia Saudí');
INSERT into imet.imet_countries VALUES ('AR', 'ARG', 32, 'Argentine', 'Argentina', 'Argentina');
INSERT into imet.imet_countries VALUES ('AM', 'ARM', 51, 'Arménie', 'Armenia', 'Armenia');
INSERT into imet.imet_countries VALUES ('AW', 'ABW', 533, 'Aruba', 'Aruba', 'Aruba');
INSERT into imet.imet_countries VALUES ('AU', 'AUS', 36, 'Australie', 'Australia', 'Australia');
INSERT into imet.imet_countries VALUES ('AT', 'AUT', 40, 'Autriche', 'Austria', 'Austria');
INSERT into imet.imet_countries VALUES ('AZ', 'AZE', 31, 'Azerbaïdjan', 'Azerbaijan', 'Azerbaiyán');
INSERT into imet.imet_countries VALUES ('BS', 'BHS', 44, 'Bahamas', 'Bahamas', 'Bahamas');
INSERT into imet.imet_countries VALUES ('BH', 'BHR', 48, 'Bahreïn', 'Bahrain', 'Bahrain');
INSERT into imet.imet_countries VALUES ('BD', 'BGD', 50, 'Bangladesh', 'Bangladesh', 'Bangladesh');
INSERT into imet.imet_countries VALUES ('BB', 'BRB', 52, 'Barbade', 'Barbados', 'Barbados');
INSERT into imet.imet_countries VALUES ('BY', 'BLR', 112, 'Bélarus', 'Belarus', 'Belarus');
INSERT into imet.imet_countries VALUES ('BE', 'BEL', 56, 'Belgique', 'Belgium', 'Bélgica');
INSERT into imet.imet_countries VALUES ('BZ', 'BLZ', 84, 'Belize', 'Belize', 'Belize');
INSERT into imet.imet_countries VALUES ('BJ', 'BEN', 204, 'Bénin', 'Benin', 'Benin');
INSERT into imet.imet_countries VALUES ('BM', 'BMU', 60, 'Bermudes', 'Bermuda', 'Bermuda');
INSERT into imet.imet_countries VALUES ('BT', 'BTN', 64, 'Bhoutan', 'Bhutan', 'Bhutan');
INSERT into imet.imet_countries VALUES ('BO', 'BOL', 68, 'Bolivie', 'Bolivia', 'Bolivia');
INSERT into imet.imet_countries VALUES ('BA', 'BIH', 70, 'Bosnie-Herzégovine', 'Bosnia and Herzegovina', 'Bosnia y Herzegovina');
INSERT into imet.imet_countries VALUES ('BW', 'BWA', 72, 'Botswana', 'Botswana', 'Botswana');
INSERT into imet.imet_countries VALUES ('BR', 'BRA', 76, 'Brésil', 'Brazil', 'Brasil');
INSERT into imet.imet_countries VALUES ('BN', 'BRN', 96, 'Brunéi Darussalam', 'Brunei Darussalam', 'Brunei Darussalam');
INSERT into imet.imet_countries VALUES ('BG', 'BGR', 100, 'Bulgarie', 'Bulgaria', 'Bulgaria');
INSERT into imet.imet_countries VALUES ('BF', 'BFA', 854, 'Burkina Faso', 'Burkina Faso', 'Burkina Faso');
INSERT into imet.imet_countries VALUES ('BI', 'BDI', 108, 'Burundi', 'Burundi', 'Burundi');
INSERT into imet.imet_countries VALUES ('KH', 'KHM', 116, 'Cambodge', 'Cambodia', 'Camboya');
INSERT into imet.imet_countries VALUES ('CM', 'CMR', 120, 'Cameroun', 'Cameroon', 'Camerún');
INSERT into imet.imet_countries VALUES ('CA', 'CAN', 124, 'Canada', 'Canada', 'Canadá');
INSERT into imet.imet_countries VALUES ('CV', 'CPV', 132, 'Cap-vert', 'Cape Verde', 'Cabo Verde');
INSERT into imet.imet_countries VALUES ('CL', 'CHL', 152, 'Chili', 'Chile', 'Chile');
INSERT into imet.imet_countries VALUES ('CN', 'CHN', 156, 'Chine', 'China', 'China');
INSERT into imet.imet_countries VALUES ('CY', 'CYP', 196, 'Chypre', 'Cyprus', 'Chipre');
INSERT into imet.imet_countries VALUES ('CO', 'COL', 170, 'Colombie', 'Colombia', 'Colombia');
INSERT into imet.imet_countries VALUES ('KM', 'COM', 174, 'Comores', 'Comoros', 'Comoros');
INSERT into imet.imet_countries VALUES ('CR', 'CRI', 188, 'Costa Rica', 'Costa Rica', 'Costa Rica');
INSERT into imet.imet_countries VALUES ('CI', 'CIV', 384, 'Côte d''Ivoire', 'Côte d''Ivoire', 'Costa de Marfil');
INSERT into imet.imet_countries VALUES ('HR', 'HRV', 191, 'Croatie', 'Croatia', 'Croacia');
INSERT into imet.imet_countries VALUES ('CU', 'CUB', 192, 'Cuba', 'Cuba', 'Cuba');
INSERT into imet.imet_countries VALUES ('DK', 'DNK', 208, 'Danemark', 'Denmark', 'Dinamarca');
INSERT into imet.imet_countries VALUES ('DJ', 'DJI', 262, 'Djibouti', 'Djibouti', 'Djibouti');
INSERT into imet.imet_countries VALUES ('DM', 'DMA', 212, 'Dominique', 'Dominica', 'Dominica');
INSERT into imet.imet_countries VALUES ('EG', 'EGY', 818, 'Égypte', 'Egypt', 'Egipto');
INSERT into imet.imet_countries VALUES ('SV', 'SLV', 222, 'El Salvador', 'El Salvador', 'El Salvador');
INSERT into imet.imet_countries VALUES ('AE', 'ARE', 784, 'Émirats Arabes Unis', 'United Arab Emirates', 'Emiratos Árabes Unidos');
INSERT into imet.imet_countries VALUES ('EC', 'ECU', 218, 'Équateur', 'Ecuador', 'Ecuador');
INSERT into imet.imet_countries VALUES ('ER', 'ERI', 232, 'Érythrée', 'Eritrea', 'Eritrea');
INSERT into imet.imet_countries VALUES ('ES', 'ESP', 724, 'Espagne', 'Spain', 'España');
INSERT into imet.imet_countries VALUES ('EE', 'EST', 233, 'Estonie', 'Estonia', 'Estonia');
INSERT into imet.imet_countries VALUES ('FM', 'FSM', 583, 'États Fédérés de Micronésie', 'Federated States of Micronesia', 'Micronesia');
INSERT into imet.imet_countries VALUES ('US', 'USA', 840, 'États-Unis', 'United States', 'Estados Unidos');
INSERT into imet.imet_countries VALUES ('ET', 'ETH', 231, 'Éthiopie', 'Ethiopia', 'Etiopía');
INSERT into imet.imet_countries VALUES ('WY', 'AWY', NULL, 'Far Far Away', 'Far Far Away', 'Far Far Away');
INSERT into imet.imet_countries VALUES ('RU', 'RUS', 643, 'Fédération de Russie', 'Russian Federation', 'Rusia');
INSERT into imet.imet_countries VALUES ('FJ', 'FJI', 242, 'Fidji', 'Fiji', 'Fiji');
INSERT into imet.imet_countries VALUES ('FI', 'FIN', 246, 'Finlande', 'Finland', 'Finlandia');
INSERT into imet.imet_countries VALUES ('FR', 'FRA', 250, 'France', 'France', 'Francia');
INSERT into imet.imet_countries VALUES ('GA', 'GAB', 266, 'Gabon', 'Gabon', 'Gabón');
INSERT into imet.imet_countries VALUES ('GM', 'GMB', 270, 'Gambie', 'Gambia', 'Gambia');
INSERT into imet.imet_countries VALUES ('GE', 'GEO', 268, 'Géorgie', 'Georgia', 'Georgia');
INSERT into imet.imet_countries VALUES ('GS', 'SGS', 239, 'Géorgie du Sud et les Îles Sandwich du Sud', 'South Georgia and the South Sandwich Islands', 'Georgia del Sur e Islas Sandwich del Sur');
INSERT into imet.imet_countries VALUES ('GH', 'GHA', 288, 'Ghana', 'Ghana', 'Ghana');
INSERT into imet.imet_countries VALUES ('GI', 'GIB', 292, 'Gibraltar', 'Gibraltar', 'Gibraltar');
INSERT into imet.imet_countries VALUES ('GR', 'GRC', 300, 'Grèce', 'Greece', 'Grecia');
INSERT into imet.imet_countries VALUES ('GD', 'GRD', 308, 'Grenade', 'Grenada', 'Granada');
INSERT into imet.imet_countries VALUES ('GL', 'GRL', 304, 'Groenland', 'Greenland', 'Groenlandia');
INSERT into imet.imet_countries VALUES ('GP', 'GLP', 312, 'Guadeloupe', 'Guadeloupe', 'Guadalupe');
INSERT into imet.imet_countries VALUES ('GU', 'GUM', 316, 'Guam', 'Guam', 'Guam');
INSERT into imet.imet_countries VALUES ('GT', 'GTM', 320, 'Guatemala', 'Guatemala', 'Guatemala');
INSERT into imet.imet_countries VALUES ('GN', 'GIN', 324, 'Guinée', 'Guinea', 'Guinea');
INSERT into imet.imet_countries VALUES ('GW', 'GNB', 624, 'Guinée-Bissau', 'Guinea-Bissau', 'Guinea-Bissau');
INSERT into imet.imet_countries VALUES ('GQ', 'GNQ', 226, 'Guinée Équatoriale', 'Equatorial Guinea', 'Guinea Ecuatorial');
INSERT into imet.imet_countries VALUES ('GY', 'GUY', 328, 'Guyana', 'Guyana', 'Guayana');
INSERT into imet.imet_countries VALUES ('GF', 'GUF', 254, 'Guyane Française', 'French Guiana', 'Guinea Francesa');
INSERT into imet.imet_countries VALUES ('HT', 'HTI', 332, 'Haïti', 'Haiti', 'Haití');
INSERT into imet.imet_countries VALUES ('HN', 'HND', 340, 'Honduras', 'Honduras', 'Honduras');
INSERT into imet.imet_countries VALUES ('HK', 'HKG', 344, 'Hong-Kong', 'Hong Kong', 'Hong Kong');
INSERT into imet.imet_countries VALUES ('HU', 'HUN', 348, 'Hongrie', 'Hungary', 'Hungría');
INSERT into imet.imet_countries VALUES ('BV', 'BVT', 74, 'Île Bouvet', 'Bouvet Island', 'Isla Bouvet');
INSERT into imet.imet_countries VALUES ('CX', 'CXR', 162, 'Île Christmas', 'Christmas Island', 'Isla Navidad');
INSERT into imet.imet_countries VALUES ('IM', 'IMN', 833, 'Île de Man', 'Isle of Man', 'Isla de Man');
INSERT into imet.imet_countries VALUES ('NF', 'NFK', 574, 'Île Norfolk', 'Norfolk Island', 'Islas Norfolk');
INSERT into imet.imet_countries VALUES ('AX', 'ALA', 248, 'Îles Åland', 'Åland Islands', 'Islas Åland');
INSERT into imet.imet_countries VALUES ('KY', 'CYM', 136, 'Îles Caïmanes', 'Cayman Islands', 'Islas Caimán');
INSERT into imet.imet_countries VALUES ('CC', 'CCK', 166, 'Îles Cocos (Keeling)', 'Cocos (Keeling) Islands', 'Islas Cocos (Keeling)');
INSERT into imet.imet_countries VALUES ('CK', 'COK', 184, 'Îles Cook', 'Cook Islands', 'Islas Cook');
INSERT into imet.imet_countries VALUES ('FO', 'FRO', 234, 'Îles Féroé', 'Faroe Islands', 'Islas Faroe');
INSERT into imet.imet_countries VALUES ('HM', 'HMD', 334, 'Îles Heard et Mcdonald', 'Heard Island and McDonald Islands', 'Islas Heard e Islas McDonald');
INSERT into imet.imet_countries VALUES ('FK', 'FLK', 238, 'Îles (malvinas) Falkland', 'Falkland Islands', 'Islas Malvinas');
INSERT into imet.imet_countries VALUES ('MP', 'MNP', 580, 'Îles Mariannes du Nord', 'Northern Mariana Islands', 'Islas de Norte-Mariana');
INSERT into imet.imet_countries VALUES ('MH', 'MHL', 584, 'Îles Marshall', 'Marshall Islands', 'Islas Marshall');
INSERT into imet.imet_countries VALUES ('UM', 'UMI', 581, 'Îles Mineures Éloignées des États-Unis', 'United States Minor Outlying Islands', 'Islas Ultramarinas de Estados Unidos');
INSERT into imet.imet_countries VALUES ('SB', 'SLB', 90, 'Îles Salomon', 'Solomon Islands', 'Islas Salomón');
INSERT into imet.imet_countries VALUES ('TC', 'TCA', 796, 'Îles Turks et Caïques', 'Turks and Caicos Islands', 'Islas Turks y Caicos');
INSERT into imet.imet_countries VALUES ('VG', 'VGB', 92, 'Îles Vierges Britanniques', 'British Virgin Islands', 'Islas Vírgenes Británicas');
INSERT into imet.imet_countries VALUES ('VI', 'VIR', 850, 'Îles Vierges des États-Unis', 'U.S. Virgin Islands', 'Islas Vírgenes Estadounidenses');
INSERT into imet.imet_countries VALUES ('IN', 'IND', 356, 'Inde', 'India', 'India');
INSERT into imet.imet_countries VALUES ('ID', 'IDN', 360, 'Indonésie', 'Indonesia', 'Indonesia');
INSERT into imet.imet_countries VALUES ('IQ', 'IRQ', 368, 'Iraq', 'Iraq', 'Irak');
INSERT into imet.imet_countries VALUES ('IE', 'IRL', 372, 'Irlande', 'Ireland', 'Irlanda');
INSERT into imet.imet_countries VALUES ('IS', 'ISL', 352, 'Islande', 'Iceland', 'Islandia');
INSERT into imet.imet_countries VALUES ('IL', 'ISR', 376, 'Israël', 'Israel', 'Israel');
INSERT into imet.imet_countries VALUES ('IT', 'ITA', 380, 'Italie', 'Italy', 'Italia');
INSERT into imet.imet_countries VALUES ('LY', 'LBY', 434, 'Jamahiriya Arabe Libyenne', 'Libyan Arab Jamahiriya', 'Libia');
INSERT into imet.imet_countries VALUES ('JM', 'JAM', 388, 'Jamaïque', 'Jamaica', 'Jamaica');
INSERT into imet.imet_countries VALUES ('JP', 'JPN', 392, 'Japon', 'Japan', 'Japón');
INSERT into imet.imet_countries VALUES ('JO', 'JOR', 400, 'Jordanie', 'Jordan', 'Jordania');
INSERT into imet.imet_countries VALUES ('KZ', 'KAZ', 398, 'Kazakhstan', 'Kazakhstan', 'Kazajstán');
INSERT into imet.imet_countries VALUES ('KE', 'KEN', 404, 'Kenya', 'Kenya', 'Kenia');
INSERT into imet.imet_countries VALUES ('KG', 'KGZ', 417, 'Kirghizistan', 'Kyrgyzstan', 'Kirgistán');
INSERT into imet.imet_countries VALUES ('KI', 'KIR', 296, 'Kiribati', 'Kiribati', 'Kiribati');
INSERT into imet.imet_countries VALUES ('KW', 'KWT', 414, 'Koweït', 'Kuwait', 'Kuwait');
INSERT into imet.imet_countries VALUES ('LS', 'LSO', 426, 'Lesotho', 'Lesotho', 'Lesoto');
INSERT into imet.imet_countries VALUES ('LV', 'LVA', 428, 'Lettonie', 'Latvia', 'Letonia');
INSERT into imet.imet_countries VALUES ('MK', 'MKD', 807, 'L''ex-République Yougoslave de Macédoine', 'The Former Yugoslav Republic of Macedonia', 'Macedonia');
INSERT into imet.imet_countries VALUES ('LB', 'LBN', 422, 'Liban', 'Lebanon', 'Líbano');
INSERT into imet.imet_countries VALUES ('LR', 'LBR', 430, 'Libéria', 'Liberia', 'Liberia');
INSERT into imet.imet_countries VALUES ('LI', 'LIE', 438, 'Liechtenstein', 'Liechtenstein', 'Liechtenstein');
INSERT into imet.imet_countries VALUES ('LT', 'LTU', 440, 'Lituanie', 'Lithuania', 'Lituania');
INSERT into imet.imet_countries VALUES ('LU', 'LUX', 442, 'Luxembourg', 'Luxembourg', 'Luxemburgo');
INSERT into imet.imet_countries VALUES ('MO', 'MAC', 446, 'Macao', 'Macao', 'Macao');
INSERT into imet.imet_countries VALUES ('MG', 'MDG', 450, 'Madagascar', 'Madagascar', 'Madagascar');
INSERT into imet.imet_countries VALUES ('MY', 'MYS', 458, 'Malaisie', 'Malaysia', 'Malasia');
INSERT into imet.imet_countries VALUES ('MW', 'MWI', 454, 'Malawi', 'Malawi', 'Malawi');
INSERT into imet.imet_countries VALUES ('MV', 'MDV', 462, 'Maldives', 'Maldives', 'Maldivas');
INSERT into imet.imet_countries VALUES ('ML', 'MLI', 466, 'Mali', 'Mali', 'Mali');
INSERT into imet.imet_countries VALUES ('MT', 'MLT', 470, 'Malte', 'Malta', 'Malta');
INSERT into imet.imet_countries VALUES ('MA', 'MAR', 504, 'Maroc', 'Morocco', 'Marruecos');
INSERT into imet.imet_countries VALUES ('MQ', 'MTQ', 474, 'Martinique', 'Martinique', 'Martinica');
INSERT into imet.imet_countries VALUES ('MU', 'MUS', 480, 'Maurice', 'Mauritius', 'Mauricio');
INSERT into imet.imet_countries VALUES ('MR', 'MRT', 478, 'Mauritanie', 'Mauritania', 'Mauritania');
INSERT into imet.imet_countries VALUES ('YT', 'MYT', 175, 'Mayotte', 'Mayotte', 'Mayote');
INSERT into imet.imet_countries VALUES ('MX', 'MEX', 484, 'Mexique', 'Mexico', 'México');
INSERT into imet.imet_countries VALUES ('MC', 'MCO', 492, 'Monaco', 'Monaco', 'Mónaco');
INSERT into imet.imet_countries VALUES ('MN', 'MNG', 496, 'Mongolie', 'Mongolia', 'Mongolia');
INSERT into imet.imet_countries VALUES ('MS', 'MSR', 500, 'Montserrat', 'Montserrat', 'Montserrat');
INSERT into imet.imet_countries VALUES ('MZ', 'MOZ', 508, 'Mozambique', 'Mozambique', 'Mozambique');
INSERT into imet.imet_countries VALUES ('MM', 'MMR', 104, 'Myanmar', 'Myanmar', 'Mianmar');
INSERT into imet.imet_countries VALUES ('NA', 'NAM', 516, 'Namibie', 'Namibia', 'Namibia');
INSERT into imet.imet_countries VALUES ('NR', 'NRU', 520, 'Nauru', 'Nauru', 'Nauru');
INSERT into imet.imet_countries VALUES ('NP', 'NPL', 524, 'Népal', 'Nepal', 'Nepal');
INSERT into imet.imet_countries VALUES ('NI', 'NIC', 558, 'Nicaragua', 'Nicaragua', 'Nicaragua');
INSERT into imet.imet_countries VALUES ('NE', 'NER', 562, 'Niger', 'Niger', 'Níger');
INSERT into imet.imet_countries VALUES ('NG', 'NGA', 566, 'Nigéria', 'Nigeria', 'Nigeria');
INSERT into imet.imet_countries VALUES ('NU', 'NIU', 570, 'Niué', 'Niue', 'Niue');
INSERT into imet.imet_countries VALUES ('NO', 'NOR', 578, 'Norvège', 'Norway', 'Noruega');
INSERT into imet.imet_countries VALUES ('NC', 'NCL', 540, 'Nouvelle-Calédonie', 'New Caledonia', 'Nueva Caledonia');
INSERT into imet.imet_countries VALUES ('NZ', 'NZL', 554, 'Nouvelle-Zélande', 'New Zealand', 'Nueva Zelanda');
INSERT into imet.imet_countries VALUES ('OM', 'OMN', 512, 'Oman', 'Oman', 'Omán');
INSERT into imet.imet_countries VALUES ('UG', 'UGA', 800, 'Ouganda', 'Uganda', 'Uganda');
INSERT into imet.imet_countries VALUES ('UZ', 'UZB', 860, 'Ouzbékistan', 'Uzbekistan', 'Uzbekistán');
INSERT into imet.imet_countries VALUES ('PK', 'PAK', 586, 'Pakistan', 'Pakistan', 'Pakistán');
INSERT into imet.imet_countries VALUES ('PW', 'PLW', 585, 'Palaos', 'Palau', 'Palau');
INSERT into imet.imet_countries VALUES ('PA', 'PAN', 591, 'Panama', 'Panama', 'Panamá');
INSERT into imet.imet_countries VALUES ('PG', 'PNG', 598, 'Papouasie-Nouvelle-Guinée', 'Papua New Guinea', 'Papúa Nueva Guinea');
INSERT into imet.imet_countries VALUES ('PY', 'PRY', 600, 'Paraguay', 'Paraguay', 'Paraguay');
INSERT into imet.imet_countries VALUES ('NL', 'NLD', 528, 'Pays-Bas', 'Netherlands', 'Holanda');
INSERT into imet.imet_countries VALUES ('PE', 'PER', 604, 'Pérou', 'Peru', 'Perú');
INSERT into imet.imet_countries VALUES ('PH', 'PHL', 608, 'Philippines', 'Philippines', 'Filipinas');
INSERT into imet.imet_countries VALUES ('PN', 'PCN', 612, 'Pitcairn', 'Pitcairn', 'Pitcairn');
INSERT into imet.imet_countries VALUES ('PL', 'POL', 616, 'Pologne', 'Poland', 'Polonia');
INSERT into imet.imet_countries VALUES ('PF', 'PYF', 258, 'Polynésie Française', 'French Polynesia', 'Polinesia Francesa');
INSERT into imet.imet_countries VALUES ('PR', 'PRI', 630, 'Porto Rico', 'Puerto Rico', 'Puerto Rico');
INSERT into imet.imet_countries VALUES ('PT', 'PRT', 620, 'Portugal', 'Portugal', 'Portugal');
INSERT into imet.imet_countries VALUES ('QA', 'QAT', 634, 'Qatar', 'Qatar', 'Qatar');
INSERT into imet.imet_countries VALUES ('SY', 'SYR', 760, 'République Arabe Syrienne', 'Syrian Arab Republic', 'Siria');
INSERT into imet.imet_countries VALUES ('CF', 'CAF', 140, 'République Centrafricaine', 'Central African', 'República Centroafricana');
INSERT into imet.imet_countries VALUES ('KR', 'KOR', 410, 'République de Corée', 'Republic of Korea', 'Corea');
INSERT into imet.imet_countries VALUES ('CD', 'COD', 180, 'République Démocratique du Congo', 'Democratic Republic Of Congo', 'República Democrática del Congo');
INSERT into imet.imet_countries VALUES ('LA', 'LAO', 418, 'République Démocratique Populaire Lao', 'Lao People''s Democratic Republic', 'Laos');
INSERT into imet.imet_countries VALUES ('MD', 'MDA', 498, 'République de Moldova', 'Republic of Moldova', 'Moldavia');
INSERT into imet.imet_countries VALUES ('DO', 'DOM', 214, 'République Dominicaine', 'Dominican Republic', 'República Dominicana');
INSERT into imet.imet_countries VALUES ('CG', 'COG', 178, 'République du Congo', 'Republic of Congo', 'Congo');
INSERT into imet.imet_countries VALUES ('IR', 'IRN', 364, 'République Islamique d''Iran', 'Islamic Republic of Iran', 'Irán');
INSERT into imet.imet_countries VALUES ('KP', 'PRK', 408, 'République Populaire Démocratique de Corée', 'Democratic People''s Republic of Korea', 'Corea');
INSERT into imet.imet_countries VALUES ('CZ', 'CZE', 203, 'République Tchèque', 'Czech Republic', 'Chequia');
INSERT into imet.imet_countries VALUES ('TZ', 'TZA', 834, 'République-Unie de Tanzanie', 'United Republic Of Tanzania', 'Tanzania');
INSERT into imet.imet_countries VALUES ('RE', 'REU', 638, 'Réunion', 'Réunion', 'Reunión');
INSERT into imet.imet_countries VALUES ('RO', 'ROU', 642, 'Roumanie', 'Romania', 'Rumanía');
INSERT into imet.imet_countries VALUES ('GB', 'GBR', 826, 'Royaume-Uni', 'United Kingdom', 'Reino Unido');
INSERT into imet.imet_countries VALUES ('RW', 'RWA', 646, 'Rwanda', 'Rwanda', 'Ruanda');
INSERT into imet.imet_countries VALUES ('EH', 'ESH', 732, 'Sahara Occidental', 'Western Sahara', 'Sáhara Occidental');
INSERT into imet.imet_countries VALUES ('SH', 'SHN', 654, 'Sainte-Hélène', 'Saint Helena', 'Santa Helena');
INSERT into imet.imet_countries VALUES ('LC', 'LCA', 662, 'Sainte-Lucie', 'Saint Lucia', 'Santa Lucía');
INSERT into imet.imet_countries VALUES ('KN', 'KNA', 659, 'Saint-Kitts-et-Nevis', 'Saint Kitts and Nevis', 'Santa Kitts y Nevis');
INSERT into imet.imet_countries VALUES ('SM', 'SMR', 674, 'Saint-Marin', 'San Marino', 'San Marino');
INSERT into imet.imet_countries VALUES ('PM', 'SPM', 666, 'Saint-Pierre-et-Miquelon', 'Saint-Pierre and Miquelon', 'San Pedro y Miquelon');
INSERT into imet.imet_countries VALUES ('VA', 'VAT', 336, 'Saint-Siège (état de la Cité du Vatican)', 'Vatican City State', 'Estado Vaticano');
INSERT into imet.imet_countries VALUES ('VC', 'VCT', 670, 'Saint-Vincent-et-les Grenadines', 'Saint Vincent and the Grenadines', 'San Vincente y Las Granadinas');
INSERT into imet.imet_countries VALUES ('WS', 'WSM', 882, 'Samoa', 'Samoa', 'Samoa');
INSERT into imet.imet_countries VALUES ('AS', 'ASM', 16, 'Samoa Américaines', 'American Samoa', 'Samoa americana');
INSERT into imet.imet_countries VALUES ('ST', 'STP', 678, 'Sao Tomé-et-Principe', 'Sao Tome and Principe', 'Santo Tomé y Príncipe');
INSERT into imet.imet_countries VALUES ('SN', 'SEN', 686, 'Sénégal', 'Senegal', 'Senegal');
INSERT into imet.imet_countries VALUES ('CS', 'SCG', 0, 'Serbie-et-Monténégro', 'Serbia and Montenegro', 'Serbia y Montenegro');
INSERT into imet.imet_countries VALUES ('SC', 'SYC', 690, 'Seychelles', 'Seychelles', 'Seychelles');
INSERT into imet.imet_countries VALUES ('SL', 'SLE', 694, 'Sierra Leone', 'Sierra Leone', 'Sierra Leona');
INSERT into imet.imet_countries VALUES ('SG', 'SGP', 702, 'Singapour', 'Singapore', 'Singapur');
INSERT into imet.imet_countries VALUES ('SK', 'SVK', 703, 'Slovaquie', 'Slovakia', 'Eslovaquia');
INSERT into imet.imet_countries VALUES ('SI', 'SVN', 705, 'Slovénie', 'Slovenia', 'Eslovenia');
INSERT into imet.imet_countries VALUES ('SO', 'SOM', 706, 'Somalie', 'Somalia', 'Somalia');
INSERT into imet.imet_countries VALUES ('SD', 'SDN', 729, 'Soudan', 'Sudan', 'Sudán');
INSERT into imet.imet_countries VALUES ('LK', 'LKA', 144, 'Sri Lanka', 'Sri Lanka', 'Sri Lanka');
INSERT into imet.imet_countries VALUES ('SE', 'SWE', 752, 'Suède', 'Sweden', 'Suecia');
INSERT into imet.imet_countries VALUES ('CH', 'CHE', 756, 'Suisse', 'Switzerland', 'Suiza');
INSERT into imet.imet_countries VALUES ('SR', 'SUR', 740, 'Suriname', 'Suriname', 'Surinám');
INSERT into imet.imet_countries VALUES ('SJ', 'SJM', 744, 'Svalbard et Île Jan Mayen', 'Svalbard and Jan Mayen', 'Esvalbard y Jan Mayen');
INSERT into imet.imet_countries VALUES ('SZ', 'SWZ', 748, 'Swaziland', 'Swaziland', 'Suazilandia');
INSERT into imet.imet_countries VALUES ('TJ', 'TJK', 762, 'Tadjikistan', 'Tajikistan', 'Tajikistán');
INSERT into imet.imet_countries VALUES ('TW', 'TWN', 158, 'Taïwan', 'Taiwan', 'Taiwán');
INSERT into imet.imet_countries VALUES ('TD', 'TCD', 148, 'Tchad', 'Chad', 'Chad');
INSERT into imet.imet_countries VALUES ('TF', 'ATF', 260, 'Terres Australes Françaises', 'French Southern Territories', 'Territorios Sureños de Francia');
INSERT into imet.imet_countries VALUES ('IO', 'IOT', 86, 'Territoire Britannique de l''Océan Indien', 'British Indian Ocean Territory', 'Territorio Oceánico de la India Británica');
INSERT into imet.imet_countries VALUES ('PS', 'PSE', 275, 'Territoire Palestinien Occupé', 'Occupied Palestinian Territory', 'Palestina');
INSERT into imet.imet_countries VALUES ('TH', 'THA', 764, 'Thaïlande', 'Thailand', 'Tailandia');
INSERT into imet.imet_countries VALUES ('TL', 'TLS', 626, 'Timor-Leste', 'Timor-Leste', 'Timor Leste');
INSERT into imet.imet_countries VALUES ('TG', 'TGO', 768, 'Togo', 'Togo', 'Togo');
INSERT into imet.imet_countries VALUES ('TK', 'TKL', 772, 'Tokelau', 'Tokelau', 'Tokelau');
INSERT into imet.imet_countries VALUES ('TO', 'TON', 776, 'Tonga', 'Tonga', 'Tongo');
INSERT into imet.imet_countries VALUES ('TT', 'TTO', 780, 'Trinité-et-Tobago', 'Trinidad and Tobago', 'Trinidad y Tobago');
INSERT into imet.imet_countries VALUES ('TN', 'TUN', 788, 'Tunisie', 'Tunisia', 'Túnez');
INSERT into imet.imet_countries VALUES ('TM', 'TKM', 795, 'Turkménistan', 'Turkmenistan', 'Turmenistán');
INSERT into imet.imet_countries VALUES ('TR', 'TUR', 792, 'Turquie', 'Turkey', 'Turquía');
INSERT into imet.imet_countries VALUES ('TV', 'TUV', 798, 'Tuvalu', 'Tuvalu', 'Tuvalu');
INSERT into imet.imet_countries VALUES ('UA', 'UKR', 804, 'Ukraine', 'Ukraine', 'Ucrania');
INSERT into imet.imet_countries VALUES ('UY', 'URY', 858, 'Uruguay', 'Uruguay', 'Uruguay');
INSERT into imet.imet_countries VALUES ('VU', 'VUT', 548, 'Vanuatu', 'Vanuatu', 'Vanuatu');
INSERT into imet.imet_countries VALUES ('VE', 'VEN', 862, 'Venezuela', 'Venezuela', 'Venezuela');
INSERT into imet.imet_countries VALUES ('VN', 'VNM', 704, 'Viet Nam', 'Vietnam', 'Vietnam');
INSERT into imet.imet_countries VALUES ('WF', 'WLF', 876, 'Wallis et Futuna', 'Wallis and Futuna', 'Wallis y Futuna');
INSERT into imet.imet_countries VALUES ('YE', 'YEM', 887, 'Yémen', 'Yemen', 'Yemen');
INSERT into imet.imet_countries VALUES ('ZM', 'ZMB', 894, 'Zambie', 'Zambia', 'Zambia');
INSERT into imet.imet_countries VALUES ('ZW', 'ZWE', 716, 'Zimbabwe', 'Zimbabwe', 'Zimbabue');

COMMIT;