BEGIN;

INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592621', 'BOL', 555592621, 'Cerro Ticani', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592622', 'BOL', 555592622, 'Jonkhomarca', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592623', 'BOL', 555592623, 'Cerro Aruntaya (23 de marzo)', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592624', 'BOL', 555592624, 'Kellumani', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592625', 'BOL', 555592625, 'Serranías de Aruntaya', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592626', 'BOL', 555592626, 'Las Animas Putupampa', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592651', 'BOL', 555592651, 'Bosque de algarrobo Tiataco', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592652', 'BOL', 555592652, 'Tacoloma', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592653', 'BOL', 555592653, 'Arenales de Cochiraya y San Pedro', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592654', 'BOL', 555592654, 'San Agustin', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342501', 'BOL', 342501, 'Area de proteccion del Pino del Cerro', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__20037', 'BOL', 20037, 'Carrasco', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__4644', 'BOL', 4644, 'Tunari', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342487', 'BOL', 342487, 'Flavio Machicado Viscarra', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342465', 'BOL', 342465, 'Yacuma', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592671', 'BOL', 555592671, 'Chuchini', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592672', 'BOL', 555592672, 'Cañon de Chuwaqueri', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592677', 'BOL', 555592677, 'Eva Eva Mosetenes', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__303896', 'BOL', 303896, 'Aguarague', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__303887', 'BOL', 303887, 'Amboró', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592627', 'BOL', 555592627, 'Huayllani', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592628', 'BOL', 555592628, 'Huallatanipampa', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592629', 'BOL', 555592629, 'Serranías Chicani', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592630', 'BOL', 555592630, 'Siete Lagunas', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592631', 'BOL', 555592631, 'Huaripampa', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592637', 'BOL', 555592637, 'Kaluyo', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592638', 'BOL', 555592638, 'Incachaca', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592639', 'BOL', 555592639, 'Chapare', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592640', 'BOL', 555592640, 'Pocotaika', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592641', 'BOL', 555592641, 'Lago San jose', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592642', 'BOL', 555592642, 'Churo Negro', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592643', 'BOL', 555592643, 'Zona de Proteccion Paisajistica', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592644', 'BOL', 555592644, 'Cerro Viscachani', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592645', 'BOL', 555592645, 'Parque Ecologico Urbano de Cobija', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592646', 'BOL', 555592646, 'Mamore Ibare', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592647', 'BOL', 555592647, 'Cotapachi', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342500', 'BOL', 342500, 'Area de proteccion del Quebracho Colorado', 'IV', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342481', 'BOL', 342481, 'El Dorado', 'IV', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342482', 'BOL', 342482, 'Estancias Elsner Espírir', 'IV', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342502', 'BOL', 342502, 'Altamachi', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342484', 'BOL', 342484, 'Estancias San Rafael', 'IV', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342490', 'BOL', 342490, 'Santa Cruz la Vieja', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342495', 'BOL', 342495, 'Area 1 Madre de Dios', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592596', 'BOL', 555592596, 'Parabanó', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592648', 'BOL', 555592648, 'Norte de Tiquipaya', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__67815', 'BOL', 67815, 'Los Lípez', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342463', 'BOL', 342463, 'Huaripampa', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592649', 'BOL', 555592649, 'Machia', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342496', 'BOL', 342496, 'Area 2 Madre de Dios', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342497', 'BOL', 342497, 'Area 3 Madre de Dios', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342498', 'BOL', 342498, 'Area 4 Madre de Dios', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342499', 'BOL', 342499, 'Corvalan', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592597', 'BOL', 555592597, 'Serrania Sararenda-Cuevo', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342503', 'BOL', 342503, 'Altamachi', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__303895', 'BOL', 303895, 'Cotapata', 'IV', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__303897', 'BOL', 303897, 'Isiboro Securé', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__303898', 'BOL', 303898, 'Pilón Lajas', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592593', 'BOL', 555592593, 'San Ignacio', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592609', 'BOL', 555592609, 'Curichi El Cuajo', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592650', 'BOL', 555592650, 'Colcapirhua', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592594', 'BOL', 555592594, 'Orquídeas del Encanto', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592595', 'BOL', 555592595, 'Jardín de Cactáceas de Bolivia', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592598', 'BOL', 555592598, 'Serrania Sararenda-Camiri', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592599', 'BOL', 555592599, 'Palmera de Sao', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592600', 'BOL', 555592600, 'Laguna Concepcion', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592601', 'BOL', 555592601, 'Laguna Quirusillas', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592602', 'BOL', 555592602, 'San Rafael', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592613', 'BOL', 555592613, 'San Nicolas', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592614', 'BOL', 555592614, 'Monteagudo', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592615', 'BOL', 555592615, 'Serranía Cordillera de los Milagros', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592616', 'BOL', 555592616, 'Cerros de Llucancari y Taraqui', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592603', 'BOL', 555592603, 'Laguna Represa Sapocó', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592604', 'BOL', 555592604, 'Tequeje', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592605', 'BOL', 555592605, 'Tres arroyos', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342462', 'BOL', 342462, 'Mallasa', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592617', 'BOL', 555592617, 'Parque de Aranjuez', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592618', 'BOL', 555592618, 'Muela del Diablo y Cerro Pachajalla', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592606', 'BOL', 555592606, 'Serrania del Tigre Alto Madidi', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592607', 'BOL', 555592607, 'Serrania de Paramarani', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592608', 'BOL', 555592608, 'Pampas del río Yacuma', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592610', 'BOL', 555592610, 'Laguna Alalay', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592619', 'BOL', 555592619, 'Laguna Cota Cota', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592620', 'BOL', 555592620, 'Cóndores Lakota', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592611', 'BOL', 555592611, 'Quebrada El Chape', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592612', 'BOL', 555592612, 'Entre Ríos', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592632', 'BOL', 555592632, 'Hampaturi', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592633', 'BOL', 555592633, 'La Cumbre (apacheta)', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592634', 'BOL', 555592634, 'El Villar', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592635', 'BOL', 555592635, 'Serrania de Ticoma', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592636', 'BOL', 555592636, 'Cerro Uchumachi', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592655', 'BOL', 555592655, 'Cabeceras del Maniqui', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592656', 'BOL', 555592656, 'Lago Tumichucua', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592657', 'BOL', 555592657, 'Lagarpampa', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592658', 'BOL', 555592658, 'Pasorapa', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592659', 'BOL', 555592659, 'Parque Urbano Central', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592660', 'BOL', 555592660, 'Bosque de Bolognia', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592661', 'BOL', 555592661, 'Gran Jardín de la Revolución', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__303891', 'BOL', 303891, 'San Matías', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592662', 'BOL', 555592662, 'Cos Challaloma-Condor Samaña, Snias Amor de Dios-Coloradas de La Florida, Co Azusinani', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592663', 'BOL', 555592663, 'Cobaipo', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592664', 'BOL', 555592664, 'Curichi La Madre', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592665', 'BOL', 555592665, 'Río Piraí', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592666', 'BOL', 555592666, 'Laguna de Marfil', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592667', 'BOL', 555592667, 'Muela del Diablo', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__9308', 'BOL', 9308, 'Estación Biológica del Beni', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__31', 'BOL', 31, 'Noel Kempff Mercado', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__98182', 'BOL', 98182, 'Cotapata', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__36', 'BOL', 36, 'Eduardo Avaroa', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__20041', 'BOL', 20041, 'Tariquía', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__32866', 'BOL', 32866, 'Cordillera de Sama', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__303885', 'BOL', 303885, 'Otuquis', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__303886', 'BOL', 303886, 'El Palmar', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__20039', 'BOL', 20039, 'Toro Toro', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__9779', 'BOL', 9779, 'Amboró', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__20034', 'BOL', 20034, 'Cavernas del Repechón', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__33', 'BOL', 33, 'Sajama', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__30', 'BOL', 30, 'Isiboro Securé', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__20011', 'BOL', 20011, 'Pilón Lajas', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__303894', 'BOL', 303894, 'Madidi', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__303893', 'BOL', 303893, 'Apolobamba', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__35', 'BOL', 35, 'Manuripi', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342483', 'BOL', 342483, 'Ríos Blanco y Negro', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342485', 'BOL', 342485, 'Tuni Condoriri', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342486', 'BOL', 342486, 'Incacasani Altamachi', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342488', 'BOL', 342488, 'Mirikiri', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342489', 'BOL', 342489, 'Huancaroma', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342491', 'BOL', 342491, 'Yura', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342492', 'BOL', 342492, 'Llica', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342493', 'BOL', 342493, 'Cerro Tapilla', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342494', 'BOL', 342494, 'Lomas de Arena', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__303899', 'BOL', 303899, 'Bruno Racua', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592668', 'BOL', 555592668, 'Valle de Tucavaca', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592678', 'BOL', 555592678, 'Humedales del Norte', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592669', 'BOL', 555592669, 'Santa Cruz La Vieja', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592670', 'BOL', 555592670, 'Rio Grande Valles Crucenos', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342461', 'BOL', 342461, 'Las Barrancas', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342464', 'BOL', 342464, 'Pedro Ignacio Muiba', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592673', 'BOL', 555592673, 'Meandros del Ichilo', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592674', 'BOL', 555592674, 'Espejillos', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342466', 'BOL', 342466, 'Kenneth Lee', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592679', 'BOL', 555592679, 'Bosquecillo de Pura Pura', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592680', 'BOL', 555592680, 'Cuchilla de Chuquiaguillo y Quebradas del río Callapa', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592675', 'BOL', 555592675, 'Poopo', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592676', 'BOL', 555592676, 'El Cardón', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592681', 'BOL', 555592681, 'Laguna Yaguaru', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592683', 'BOL', 555592683, 'Parque Ecológico Auquisamaña', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592682', 'BOL', 555592682, 'Lagunas Santa Barbara y Brava', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592684', 'BOL', 555592684, 'Valle de la Luna y Cactareo', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555592685', 'BOL', 555592685, 'Itenez', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__342468', 'BOL', 342468, 'Iñao', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__303884', 'BOL', 303884, 'Kaa-iya del Gran Chaco', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__98183', 'BOL', 98183, 'Madidi', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__303883', 'BOL', 303883, 'Otuquis', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__2037', 'BOL', 2037, 'Parque Nacional Pilón-Lajas', 'Not Applicable', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__12472', 'BOL', 12472, 'Estación Biológica Beni', 'Not Applicable', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__220295', 'BOL', 220295, 'Noel Kempff Mercado National Park', 'Not Applicable', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__166865', 'BOL', 166865, 'Lago Titicaca', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__220050', 'BOL', 220050, 'Cuenca de Tajzara', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__900565', 'BOL', 900565, 'Bañados del Izozog y el río Parapetí', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__900566', 'BOL', 900566, 'Palmar de las Islas y las Salinas de San José', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__900567', 'BOL', 900567, 'Pantanal Boliviano', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__900784', 'BOL', 900784, 'Laguna Concepción', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__900783', 'BOL', 900783, 'Lagos Poopó y Uru Uru', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555558386', 'BOL', 555558386, 'Río Blanco', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555558387', 'BOL', 555558387, 'Río Matos', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__555558388', 'BOL', 555558388, 'Río Yata', 'Not Reported', null);
INSERT INTO imet.imet_pas (global_id, country, wdpa_id, name, iucn_category, creation_date) VALUES ('xxx__41', 'BOL', 41, 'Reserva Nacional de Fauna "Ulla Ulla"', 'Not Applicable', null);

COMMIT;
